#pragma once
#include "Object.h"
#include "Timestamp.h"
#include "Containers.h"

enum human_movement_states
{
    HMS_CURRENT = 0xFFFFFFFF,
    HMS_IDLE = 0x0,
    HMS_WALK = 0x1,
    HMS_RUN = 0x2,
    HMS_SPRINT = 0x3,
    NUM_HUMAN_MOVEMENT_STATES = 0x4,
};

enum human_path_actions
{
    HPA_NORMAL = 0x0,
    HPA_STARTUP = 0x1,
    HPA_WAIT = 0x2,
    HPA_STEER = 0x3,
};

enum object_hit_location
{
    HIT_NONE = 0xFFFFFFFF,
    HIT_GENERAL = 0x0,
    HIT_TORSO = 0x1,
    HIT_PELVIS = 0x2,
    HIT_LEFT_ARM = 0x3,
    HIT_RIGHT_ARM = 0x4,
    HIT_HEAD = 0x5,
    HIT_LEFT_LEG = 0x6,
    HIT_RIGHT_LEG = 0x7,
    NUM_HIT_LOCATIONS = 0x8,
};

enum foot_plant
{
    FP_LEFT_FOOT = 0x0,
    FP_RIGHT_FOOT = 0x1,
    FP_NEITHER_FOOT = 0x2,
    FP_BOTH_FEET = 0x3,
};

enum vehicle_seat_index
{
    VSI_BEST = 0xFFFFFFFE,
    VSI_INVALID = 0xFFFFFFFF,
    VSI_DRIVER = 0x0,
    VSI_PASSENGER_1 = 0x1,
    VSI_PASSENGER_2 = 0x2,
    VSI_PASSENGER_3 = 0x3,
    VSI_PASSENGER_4 = 0x4,
    VSI_PASSENGER_5 = 0x5,
    VSI_PASSENGER_6 = 0x6,
    VSI_PASSENGER_7 = 0x7,
    VSI_PASSENGER_8 = 0x8,
    VSI_PASSENGER_9 = 0x9,
    VSI_PASSENGER_10 = 0xA,
    NUM_VEHICLE_SEATS = 0xB,
};

enum object_importance_level
{
    OBJECT_IMPORTANCE_LEVEL_UNKNOWN = 0xFFFFFFFF,
    OBJECT_IMPORTANCE_LEVEL_NONE = 0x0,
    OBJECT_IMPORTANCE_LEVEL_LOW = 0x1,
    OBJECT_IMPORTANCE_LEVEL_MEDIUM = 0x2,
    OBJECT_IMPORTANCE_LEVEL_HIGH = 0x3,
    NUM_OBJECT_IMPORTANCE_LEVELS = 0x4,
};

enum human_rotate_dir
{
    HUMAN_ROTATE_SHORTEST = 0x0,
    HUMAN_ROTATE_CLOCKWISE = 0x1,
    HUMAN_ROTATE_COUNTERCLOCKWISE = 0x2,
    HUMAN_ROTATE_USE_LIMITS = 0x3,
};

enum block_movement_types
{
    BLOCK_MOVEMENT_POS = 0x0,
    BLOCK_MOVEMENT_ORIENT = 0x1,
    BLOCK_MOVEMENT_POS_AND_ORIENT = 0x2,
};

enum human_states
{
    HS_CURRENT = 0xFFFFFFFF,
    HS_STANDARD = 0x0,
    HS_JUMP = 0x1,
    HS_FALL = 0x2,
    HS_TURRET = 0x3,
    HS_DEAD = 0x4,
    HS_LADDER = 0x5,
    HS_PLAYER_PATHING = 0x6,
    HS_VEHICLE_ENTERING = 0x7,
    HS_VEHICLE_SITTING = 0x8,
    HS_VEHICLE_DRIVING = 0x9,
    HS_VEHICLE_EXITING = 0xA,
    HS_SPECTATOR = 0xB,
    HS_COVER = 0xC,
    HS_AMMO_BOX = 0xD,
    HS_MP_DEFUSE = 0xE,
    HS_ACTION_NODE = 0xF,
    HS_SATELLITE = 0x10,
    NUM_HUMAN_STATES = 0x11,
};

enum human_stances
{
    HST_CURRENT = 0xFFFFFFFF,
    HST_STAND = 0x0,
    HST_CROUCH = 0x1,
    HST_PRONE = 0x2,
    NUM_HUMAN_STANCES = 0x3,
};

enum human_move_modes
{
    HMM_NONE = 0x0,
    HMM_DIRECT = 0x1,
    HMM_PATHFINDING = 0x2,
    HMM_PATHFINDING_TO_VEHICLE = 0x3,
    HMM_JUMP = 0x4,
    HMM_FALL = 0x5,
    HMM_FP_MOVE = 0x6,
    HMM_KNOCKDOWN = 0x7,
    HMM_SATELLITE = 0x8,
    NUM_HUMAN_MOVE_MODES = 0x9,
};

enum human_move_submodes
{
    HMSM_NONE = 0x0,
    HMSM_JUMP_START = 0x1,
    HMSM_JUMP_PRE = 0x2,
    HMSM_JUMP_MID = 0x3,
    HMSM_FALL_START = 0x4,
    HMSM_FALL_NORMAL = 0x5,
    HMSM_FALL_WORRY = 0x6,
    HMSM_FALL_PANIC = 0x7,
    HMSM_FALL_FREE = 0x8,
    HMSM_LAND = 0x9,
    HMSM_KNOCKDOWN_RAGDOLL = 0xA,
    HMSM_KNOCKDOWN_GETUP = 0xB,
    HMSM_KNOCKDOWN_TELEPORT = 0xC,
    HMSM_PTV_PATHFINDING = 0xD,
    HMSM_PTV_PAUSED = 0xE,
    HMSM_PTV_FINAL_ADJUSTMENT = 0xF,
    HMSM_COVER_RIGHT = 0x10,
    HMSM_COVER_RIGHT_EDGE = 0x11,
    HMSM_COVER_LEFT = 0x12,
    HMSM_COVER_LEFT_EDGE = 0x13,
    HMSM_COVER_RIGHT_LEAN = 0x14,
    HMSM_COVER_LEFT_LEAN = 0x15,
    HMSM_COVER_RIGHT_LEANUP = 0x16,
    HMSM_COVER_LEFT_LEANUP = 0x17,
    HMSM_COVER_RIGHT_BLINDFIRE = 0x18,
    HMSM_COVER_LEFT_BLINDFIRE = 0x19,
    HMSM_COVER_RIGHT_BLINDFIRE2 = 0x1A,
    HMSM_COVER_LEFT_BLINDFIRE2 = 0x1B,
    NUM_HUMAN_MOVE_SUBMODES = 0x1C,
};

enum audiolib_cue_priority
{
    AUDIOLIB_CUE_PRIORITY_INVALID = 0xFFFFFFFF,
    AUDIOLIB_CUE_PRIORITY_LOW = 0x0,
    AUDIOLIB_CUE_PRIORITY_VOICE_ANIMATION = 0x1,
    AUDIOLIB_CUE_PRIORITY_DIALOGUE_AMBIENT = 0x2,
    AUDIOLIB_CUE_PRIORITY_VOICE_AMBIENT = 0x3,
    AUDIOLIB_CUE_PRIORITY_MEDIUM = 0x4,
    AUDIOLIB_CUE_PRIORITY_DIALOGUE_RADIO = 0x5,
    AUDIOLIB_CUE_PRIORITY_DIALOGUE_NORMAL = 0x6,
    AUDIOLIB_CUE_PRIORITY_HIGH = 0x7,
    AUDIOLIB_CUE_PRIORITY_DIALOGUE_HIGH = 0x8,
    AUDIOLIB_CUE_PRIORITY_DIALOGUE_BRIEFING = 0x9,
    AUDIOLIB_CUE_PRIORITY_VERY_HIGH = 0xA,
    AUDIOLIB_CUE_PRIORITY_MUSIC = 0xB,
    NUM_AUDIOLIB_CUE_PRIORITIES = 0xC,
};

enum voice_line_priorities
{
    VOICE_LINE_PRIORITY_NONE = 0x0,
    VOICE_LINE_PRIORITY_VERY_LOW = 0x1,
    VOICE_LINE_PRIORITY_LOW = 0x2,
    VOICE_LINE_PRIORITY_NORMAL = 0x3,
    VOICE_LINE_PRIORITY_HIGH = 0x4,
    VOICE_LINE_PRIORITY_VERY_HIGH = 0x5,
    VOICE_LINE_PRIORITY_CRITICAL = 0x9,
    VOICE_LINE_PRIORITY_FORCE_ALWAYS = 0xA,
    NUM_VOICE_LINE_PRIORITIES = 0xB,
    VOICE_LINE_PRIORITY_MIN_INTERRUPT_LEVEL = 0x9,
};

enum human_teams
{
    HUMAN_TEAM_NONE = 0xFFFFFFFF,
    HUMAN_TEAM_GUERILLA = 0x0,
    HUMAN_TEAM_EDF = 0x1,
    HUMAN_TEAM_CIVILIAN = 0x2,
    HUMAN_TEAM_MP_NEUTRAL = 0x2,
    HUMAN_TEAM_MARAUDER = 0x3,
    HUMAN_TEAM_MP_SPECTATOR = 0x3,
    NUM_HUMAN_TEAMS = 0x4,
};

enum voice_line_handle
{
    INVALID_VOICE_LINE_HANDLE = 0xFFFFFFFF,
    VOICE_LINE_HANDLE_IS_DLC = 0x8000,
    VOICE_LINE_HANDLE_FORCE_TO_32_BIT = 0x7FFFFFFF,
};

enum voice_lines
{
    VOICE_LINE_NONE = 0xFFFFFFFF,
    VOICE_LINE_HA_EDF_HOSTAGE_RESPONSE = 0x0,
    VOICE_LINE_HA_EDF_SPOT_PLAYER = 0x1,
    VOICE_LINE_HA_HOSTAGE_HELP = 0x2,
    VOICE_LINE_HA_HOSTAGE_HELP_PC = 0x3,
    VOICE_LINE_HA_HOSTAGE_FREED = 0x4,
    VOICE_LINE_HA_HOSTAGE_CHAT = 0x5,
    VOICE_LINE_HA_HOSTAGE_VEH_CHAT = 0x6,
    VOICE_LINE_HA_HOSTAGE_VEH_COMPLAINT = 0x7,
    VOICE_LINE_HA_HOSTAGE_THANK = 0x8,
    VOICE_LINE_RAID_FALL_BACK = 0x9,
    VOICE_LINE_RAID_FALL_BACK_RESPONSE = 0xA,
    VOICE_LINE_RAID_PUSH_FORWARD = 0xB,
    VOICE_LINE_RAID_PUSH_FORWARD_RESPONSE = 0xC,
    VOICE_LINE_RAID_OFFENSE_PLAYER_ARRIVES = 0xD,
    VOICE_LINE_RAID_DEFENSE_PLAYER_ARRIVES = 0xE,
    VOICE_LINE_RAID_PREPARE = 0xF,
    VOICE_LINE_RAID_PLAYER_LEAVES = 0x10,
    VOICE_LINE_RAID_REACT_EDF_REINFORCEMENTS = 0x11,
    VOICE_LINE_RAID_REACT_GUERILLA_REINFORCEMENTS = 0x12,
    VOICE_LINE_RAID_OFFENSE_WIN = 0x13,
    VOICE_LINE_RAID_DEFENSE_WIN = 0x14,
    VOICE_LINE_RAID_WIN_CHEER = 0x15,
    VOICE_LINE_VEHICLE_ATTACKED = 0x16,
    VOICE_LINE_VEHICLE_IMPACTS_VEHICLE = 0x17,
    VOICE_LINE_VEHICLE_DODGE_FRIENDLY = 0x18,
    VOICE_LINE_VEHICLE_DODGE_UNFRIENDLY = 0x19,
    VOICE_LINE_VEHICLE_SACRIFICE = 0x1A,
    VOICE_LINE_VEHICLE_SACRIFICE_RELUCTANT = 0x1B,
    VOICE_LINE_VEHICLE_STUCK = 0x1C,
    VOICE_LINE_CIVILIAN_COWER_EDF = 0x1D,
    VOICE_LINE_CIVILIAN_FLEE_EDF = 0x1E,
    VOICE_LINE_CIVILIAN_SPOT_EDF_AND_LEAVE = 0x1F,
    VOICE_LINE_PATROL_CHECK_IN = 0x20,
    VOICE_LINE_PATROL_BEAT_CIVILIAN = 0x21,
    VOICE_LINE_PATROL_BEAT_CIVILIAN_SUBMISSIVE_RESPONSE = 0x22,
    VOICE_LINE_PATROL_BEAT_CIVILIAN_EDF_RESPONSE = 0x23,
    VOICE_LINE_PATROL_REQUEST_MOVE = 0x24,
    VOICE_LINE_PATROL_REQUEST_MOVE_CIVILIAN_DEFIANT_RESPONSE = 0x25,
    VOICE_LINE_PATROL_REQUEST_MOVE_CIVILIAN_SUBMISSIVE_RESPONSE = 0x26,
    VOICE_LINE_PATROL_STOMP_CIVILIAN = 0x27,
    VOICE_LINE_PATROL_TAUNT_CIVILIAN = 0x28,
    VOICE_LINE_PATROL_TAUNT_CIVILIAN_DEFIANT_RESPONSE = 0x29,
    VOICE_LINE_AMBIENT_PLAYER_DONT_FOLLOW_ME = 0x2A,
    VOICE_LINE_AMBIENT_TALK_TO_SELF_LOW_MORALE = 0x2B,
    VOICE_LINE_AMBIENT_TALK_TO_SELF_MEDIUM_MORALE = 0x2C,
    VOICE_LINE_AMBIENT_TALK_TO_SELF_HIGH_MORALE = 0x2D,
    VOICE_LINE_AMBIENT_PLAYER_GREET_LOW_MORALE = 0x2E,
    VOICE_LINE_AMBIENT_PLAYER_GREET_MEDIUM_MORALE = 0x2F,
    VOICE_LINE_AMBIENT_PLAYER_GREET_HIGH_MORALE = 0x30,
    VOICE_LINE_AMBIENT_PLAYER_GREET_LOW_MORALE_FAMOUS = 0x31,
    VOICE_LINE_AMBIENT_PLAYER_GREET_MEDIUM_MORALE_FAMOUS = 0x32,
    VOICE_LINE_AMBIENT_PLAYER_GREET_HIGH_MORALE_FAMOUS = 0x33,
    VOICE_LINE_HONKED_AT_RESIST = 0x34,
    VOICE_LINE_HONKED_AT_MOVE = 0x35,
    VOICE_LINE_AMBIENT_THREATEN = 0x36,
    VOICE_LINE_REACT_ALLY_CORPSE_GROUP = 0x37,
    VOICE_LINE_REACT_CHARGE_GROUP = 0x38,
    VOICE_LINE_REACT_DISTURBANCE_GROUP = 0x39,
    VOICE_LINE_COMBAT_ALLY_FLEE = 0x3A,
    VOICE_LINE_COMBAT_ALLY_JOIN = 0x3B,
    VOICE_LINE_COMBAT_CONGRATULATE_ON_KILL = 0x3C,
    VOICE_LINE_COMBAT_ALLY_KILLED = 0x3D,
    VOICE_LINE_COMBAT_FRIENDLY_FIRE_ASSAILANT = 0x3E,
    VOICE_LINE_COMBAT_FRIENDLY_FIRE_OBSERVED = 0x3F,
    VOICE_LINE_COMBAT_FRIENDLY_FIRE_VICTIM = 0x40,
    VOICE_LINE_COMBAT_FRIENDLY_FIRE_VIP_COMPLAIN = 0x41,
    VOICE_LINE_COMBAT_BOOST_TEAM_MORALE = 0x42,
    VOICE_LINE_COMBAT_FLEE_COLLAPSING_BUILDING = 0x43,
    VOICE_LINE_COMBAT_VEHICLE_ABOUT_TO_BLOW = 0x44,
    VOICE_LINE_COMBAT_TAUNT_ENEMY = 0x45,
    VOICE_LINE_COMBAT_TAUNT_ENEMY_VEHICLE = 0x46,
    VOICE_LINE_COMBAT_TAUNT_ENEMY_WALKER = 0x47,
    VOICE_LINE_COMBAT_TAUNT_ENEMY_TANK = 0x48,
    VOICE_LINE_COMBAT_TAUNT_EDF = 0x49,
    VOICE_LINE_COMBAT_TAUNT_GUERILLA = 0x4A,
    VOICE_LINE_COMBAT_TAUNT_MARAUDER = 0x4B,
    VOICE_LINE_COMBAT_SPOT_ENEMY_VEHICLE = 0x4C,
    VOICE_LINE_COMBAT_SPOT_MARAUDER_TO_ALLIES = 0x4D,
    VOICE_LINE_COMBAT_SPOT_EDF_TO_ALLIES = 0x4E,
    VOICE_LINE_COMBAT_FLEE_ENEMY_TANK = 0x4F,
    VOICE_LINE_COMBAT_FLEE_ENEMY_WALKER = 0x50,
    VOICE_LINE_COMBAT_REQUEST_COVER_ME = 0x51,
    VOICE_LINE_COMBAT_REQUEST_COVER_ME_RESPONSE_NO = 0x52,
    VOICE_LINE_COMBAT_REQUEST_COVER_ME_RESPONSE_YES = 0x53,
    VOICE_LINE_COMBAT_THROW_GRENADE_GROUP = 0x54,
    VOICE_LINE_COMBAT_SPOT_GRENADE_GROUP = 0x55,
    VOICE_LINE_COMBAT_SPOT_PROJECTILE_GROUP = 0x56,
    VOICE_LINE_SEARCH_INITIATE = 0x57,
    VOICE_LINE_SEARCH_INITIATE_RESPONSE = 0x58,
    VOICE_LINE_SEARCH_THREATEN_AREA = 0x59,
    VOICE_LINE_SEARCH_DISGRUNTLED = 0x5A,
    VOICE_LINE_SEARCH_SPOT_ENEMY = 0x5B,
    VOICE_LINE_CHECKPOINT_WAVE_THROUGH = 0x5C,
    VOICE_LINE_RESTRICTED_SPOT = 0x5D,
    VOICE_LINE_RESTRICTED_FIRST_WARNING = 0x5E,
    VOICE_LINE_RESTRICTED_WARNING_SHOT = 0x5F,
    VOICE_LINE_RESTRICTED_INITIATE_BEATDOWN = 0x60,
    VOICE_LINE_RESTRICTED_TARGET_HOSTILE = 0x61,
    VOICE_LINE_RESTRICTED_TAUNT = 0x62,
    VOICE_LINE_DEMAND_CIV_ID = 0x63,
    VOICE_LINE_CIV_ID_CLEAN = 0x64,
    VOICE_LINE_CIV_ID_UNCLEAN = 0x65,
    VOICE_LINE_EXECUTE_SETUP = 0x66,
    VOICE_LINE_EXECUTE = 0x67,
    VOICE_LINE_REACT_TO_PLAYER_WEAPON = 0x68,
    VOICE_LINE_REACT_TO_PLAYER_JETPACK = 0x69,
    VOICE_LINE_UPGRADE_GENERIC = 0x6A,
    VOICE_LINE_UPGRADE_DETECTOR = 0x6B,
    VOICE_LINE_UPGRADE_GRINDER = 0x6C,
    VOICE_LINE_UPGRADE_JETPACK = 0x6D,
    VOICE_LINE_UPGRADE_PROXIMITY = 0x6E,
    VOICE_LINE_UPGRADE_RPG = 0x6F,
    VOICE_LINE_UPGRADE_SHIELDING = 0x70,
    VOICE_LINE_UPGRADE_THERMOBERIC = 0x71,
    VOICE_LINE_UPGRADE_WELDER = 0x72,
    VOICE_LINE_BATTLE_CRY = 0x73,
    VOICE_LINE_PAIN_BLUNT = 0x74,
    VOICE_LINE_BOMB = 0x75,
    VOICE_LINE_CHEER = 0x76,
    VOICE_LINE_COUGH = 0x77,
    VOICE_LINE_DEATH = 0x78,
    VOICE_LINE_DEATH_SCREAM = 0x79,
    VOICE_LINE_PAIN_ELECTRIC = 0x7A,
    VOICE_LINE_FLINCH = 0x7B,
    VOICE_LINE_PAIN_BULLET = 0x7C,
    VOICE_LINE_PANIC = 0x7D,
    VOICE_LINE_THROWN = 0x7E,
    VOICE_LINE_EDF_VEHICLE_CHASE = 0x7F,
    VOICE_LINE_MARAUDER_AMBUSH = 0x80,
    NUM_VOICE_LINES = 0x81,
};

enum animation_action
{
    ANIMATION_ACTION_NONE = 0xFFFFFFFF,
    ANIMATION_ACTION_IDLE_A = 0x142,
    ANIMATION_ACTION_IDLE_B = 0x143,
    ANIMATION_ACTION_TALK_BRIEF = 0x144,
    ANIMATION_ACTION_SIT_TO_STAND = 0x145,
    ANIMATION_ACTION_STAND_TO_SIT = 0x146,
    ANIMATION_ACTION_SLEEP_TO_STAND = 0x147,
    ANIMATION_ACTION_STAND_TO_SLEEP = 0x148,
    ANIMATION_ACTION_SLEEP_IDLE = 0x149,
    ANIMATION_ACTION_STAND_TO_RUN = 0x14A,
    ANIMATION_ACTION_WALK_TO_RUN = 0x14B,
    ANIMATION_ACTION_RUN_TO_STAND = 0x14C,
    ANIMATION_ACTION_RUN_TO_WALK = 0x14D,
    ANIMATION_ACTION_STAND_TO_CROUCH = 0x14E,
    ANIMATION_ACTION_CROUCH_TO_STAND = 0x14F,
    ANIMATION_ACTION_STAND_READY_TO_CROUCH_READY = 0x150,
    ANIMATION_ACTION_CROUCH_READY_TO_STAND_READY = 0x151,
    ANIMATION_ACTION_STAND_TO_STAND_READY = 0x152,
    ANIMATION_ACTION_CROUCH_TO_CROUCH_READY = 0x153,
    ANIMATION_ACTION_STAND_READY_TO_STAND = 0x154,
    ANIMATION_ACTION_CROUCH_READY_TO_CROUCH = 0x155,
    ANIMATION_ACTION_GUARD_LOOK_AROUND = 0x156,
    ANIMATION_ACTION_GUARD_CHECK_WEAPON = 0x157,
    ANIMATION_ACTION_GUARD_SHADE_EYES = 0x158,
    ANIMATION_ACTION_GUARD_WEAPON_MOTION = 0x159,
    ANIMATION_ACTION_GUARD_SHOVE = 0x15A,
    ANIMATION_ACTION_GUARD_BEAT_DOWN = 0x15B,
    ANIMATION_ACTION_GUARD_WARNING_SHOT = 0x15C,
    ANIMATION_ACTION_GUARD_THREATEN = 0x15D,
    ANIMATION_ACTION_GUARD_INSPECT = 0x15E,
    ANIMATION_ACTION_GUARD_POINT = 0x15F,
    ANIMATION_ACTION_STAND_COWER_INCOMING_FRONT = 0x160,
    ANIMATION_ACTION_STAND_COWER_INCOMING_LEFT = 0x161,
    ANIMATION_ACTION_STAND_COWER_INCOMING_RIGHT = 0x162,
    ANIMATION_ACTION_COWER_TO_STAND = 0x163,
    ANIMATION_ACTION_STAND_TO_COWER = 0x164,
    ANIMATION_ACTION_STAND_TO_PRONE = 0x165,
    ANIMATION_ACTION_FACEDOWN_TO_FETAL = 0x166,
    ANIMATION_ACTION_FACEUP_TO_FETAL = 0x167,
    ANIMATION_ACTION_FETAL_FLINCH = 0x168,
    ANIMATION_ACTION_REACT_AND_FLEE = 0x169,
    ANIMATION_ACTION_CALM_FALL = 0x16A,
    ANIMATION_ACTION_CALM_FALL_RUN = 0x16B,
    ANIMATION_ACTION_LAND_NORMAL = 0x16C,
    ANIMATION_ACTION_LAND_NORMAL_STOP = 0x16D,
    ANIMATION_ACTION_LAND_RUN = 0x16E,
    ANIMATION_ACTION_LAND_RUN_STOP = 0x16F,
    ANIMATION_ACTION_LAND_HARD = 0x170,
    ANIMATION_ACTION_LAND_HARD_SLAM = 0x171,
    ANIMATION_ACTION_LAND_MELEE_RUN = 0x172,
    ANIMATION_ACTION_LAND_MELEE_STOP = 0x173,
    ANIMATION_ACTION_LAND_MELEE_HARD = 0x174,
    ANIMATION_ACTION_LAND_LIGHT = 0x175,
    ANIMATION_ACTION_STAND_SHUFFLE_LEFT = 0x176,
    ANIMATION_ACTION_STAND_SHUFFLE_RIGHT = 0x177,
    ANIMATION_ACTION_STAND_READY_SHUFFLE_LEFT = 0x178,
    ANIMATION_ACTION_STAND_READY_SHUFFLE_RIGHT = 0x179,
    ANIMATION_ACTION_STAND_SHUFFLE_LEFT_180 = 0x17A,
    ANIMATION_ACTION_STAND_SHUFFLE_RIGHT_180 = 0x17B,
    ANIMATION_ACTION_CROUCH_SHUFFLE_LEFT = 0x17C,
    ANIMATION_ACTION_CROUCH_SHUFFLE_RIGHT = 0x17D,
    ANIMATION_ACTION_CROUCH_READY_SHUFFLE_LEFT = 0x17E,
    ANIMATION_ACTION_CROUCH_READY_SHUFFLE_RIGHT = 0x17F,
    ANIMATION_ACTION_CROUCH_SHUFFLE_LEFT_180 = 0x180,
    ANIMATION_ACTION_CROUCH_SHUFFLE_RIGHT_180 = 0x181,
    ANIMATION_ACTION_COMBAT_ROLL_LEFT = 0x182,
    ANIMATION_ACTION_COMBAT_ROLL_RIGHT = 0x183,
    ANIMATION_ACTION_STAND_DODGE_LEFT = 0x184,
    ANIMATION_ACTION_STAND_DODGE_RIGHT = 0x185,
    ANIMATION_ACTION_RUN_DODGE_LEFT = 0x186,
    ANIMATION_ACTION_RUN_DODGE_RIGHT = 0x187,
    ANIMATION_ACTION_SPIN_DODGE = 0x188,
    ANIMATION_ACTION_SPIN_DODGE_MOVING = 0x189,
    ANIMATION_ACTION_DIVE = 0x18A,
    ANIMATION_ACTION_DIVE_A = 0x18B,
    ANIMATION_ACTION_JUMP_FROM_BUILDING = 0x18C,
    ANIMATION_ACTION_LAND_FROM_BUILDING = 0x18D,
    ANIMATION_ACTION_LEAP_OVER = 0x18E,
    ANIMATION_ACTION_LEAP_OVER_2 = 0x18F,
    ANIMATION_ACTION_JUMP_DOWN = 0x190,
    ANIMATION_ACTION_RUN_JUMP_START = 0x191,
    ANIMATION_ACTION_STAND_JUMP_START = 0x192,
    ANIMATION_ACTION_TURN_LEFT_WALK = 0x193,
    ANIMATION_ACTION_TURN_RIGHT_WALK = 0x194,
    ANIMATION_ACTION_TURN_BACK_WALK = 0x195,
    ANIMATION_ACTION_TURN_LEFT_RUN = 0x196,
    ANIMATION_ACTION_TURN_RIGHT_RUN = 0x197,
    ANIMATION_ACTION_TURN_BACK_RUN = 0x198,
    ANIMATION_ACTION_STAND_FIRE = 0x199,
    ANIMATION_ACTION_WALK_FIRE = 0x19A,
    ANIMATION_ACTION_WALK_FIRE_BACK = 0x19B,
    ANIMATION_ACTION_WALK_FIRE_LEFT = 0x19C,
    ANIMATION_ACTION_WALK_FIRE_RIGHT = 0x19D,
    ANIMATION_ACTION_RUN_FIRE = 0x19E,
    ANIMATION_ACTION_RUN_FIRE_BACK = 0x19F,
    ANIMATION_ACTION_RUN_FIRE_LEFT = 0x1A0,
    ANIMATION_ACTION_RUN_FIRE_RIGHT = 0x1A1,
    ANIMATION_ACTION_CROUCH_FIRE = 0x1A2,
    ANIMATION_ACTION_CROUCH_WALK_FIRE = 0x1A3,
    ANIMATION_ACTION_CROUCH_WALK_FIRE_LEFT = 0x1A4,
    ANIMATION_ACTION_CROUCH_WALK_FIRE_RIGHT = 0x1A5,
    ANIMATION_ACTION_CROUCH_WALK_FIRE_BACK = 0x1A6,
    ANIMATION_ACTION_DRIVE_FIRE = 0x1A7,
    ANIMATION_ACTION_DRIVE_FIRE_LEFT = 0x1A8,
    ANIMATION_ACTION_DRIVE_FIRE_RIGHT = 0x1A9,
    ANIMATION_ACTION_RIDE_FIRE = 0x1AA,
    ANIMATION_ACTION_RIDE_FIRE_LEFT = 0x1AB,
    ANIMATION_ACTION_RIDE_FIRE_RIGHT = 0x1AC,
    ANIMATION_ACTION_RIDE_FIRE_BACK = 0x1AD,
    ANIMATION_ACTION_RIDE_LEFT_FIRE = 0x1AE,
    ANIMATION_ACTION_RIDE_LEFT_FIRE_LEFT = 0x1AF,
    ANIMATION_ACTION_RIDE_LEFT_FIRE_RIGHT = 0x1B0,
    ANIMATION_ACTION_RIDE_LEFT_FIRE_BACK = 0x1B1,
    ANIMATION_ACTION_COVER_STAND_LEFT_LEAN_FIRE = 0x1B2,
    ANIMATION_ACTION_COVER_STAND_LEFT_STEPOUT_FIRE = 0x1B3,
    ANIMATION_ACTION_COVER_STAND_LEFT_BLIND_FIRE = 0x1B4,
    ANIMATION_ACTION_COVER_STAND_LEFT_AIM_FIRE = 0x1B5,
    ANIMATION_ACTION_COVER_STAND_LEFT_AIM_WALK_FIRE = 0x1B6,
    ANIMATION_ACTION_COVER_STAND_LEFT_AIM_WALK_BACK_FIRE = 0x1B7,
    ANIMATION_ACTION_COVER_STAND_RIGHT_LEAN_FIRE = 0x1B8,
    ANIMATION_ACTION_COVER_STAND_RIGHT_STEPOUT_FIRE = 0x1B9,
    ANIMATION_ACTION_COVER_STAND_RIGHT_BLIND_FIRE = 0x1BA,
    ANIMATION_ACTION_COVER_STAND_RIGHT_AIM_FIRE = 0x1BB,
    ANIMATION_ACTION_COVER_CROUCH_RIGHT_AIM_FIRE = 0x1BC,
    ANIMATION_ACTION_COVER_CROUCH_LEFT_AIM_FIRE = 0x1BD,
    ANIMATION_ACTION_COVER_CROUCH_LEFT_TO_READY = 0x1BE,
    ANIMATION_ACTION_COVER_CROUCH_RIGHT_TO_READY = 0x1BF,
    ANIMATION_ACTION_COVER_CROUCH_LEFT_LEAN_FIRE = 0x1C0,
    ANIMATION_ACTION_COVER_CROUCH_LEFT_STEPOUT_FIRE = 0x1C1,
    ANIMATION_ACTION_COVER_CROUCH_LEFT_BLIND_FIRE = 0x1C2,
    ANIMATION_ACTION_COVER_CROUCH_LEFT_LEANUP_FIRE = 0x1C3,
    ANIMATION_ACTION_COVER_CROUCH_RIGHT_LEAN_FIRE = 0x1C4,
    ANIMATION_ACTION_COVER_CROUCH_RIGHT_STEPOUT_FIRE = 0x1C5,
    ANIMATION_ACTION_COVER_CROUCH_RIGHT_BLIND_FIRE = 0x1C6,
    ANIMATION_ACTION_COVER_CROUCH_RIGHT_LEANUP_FIRE = 0x1C7,
    ANIMATION_ACTION_COVER_CROUCH_READY_LEFT_WALK_FIRE = 0x1C8,
    ANIMATION_ACTION_COVER_CROUCH_READY_LEFT_FIRE = 0x1C9,
    ANIMATION_ACTION_COVER_CROUCH_READY_RIGHT_WALK_FIRE = 0x1CA,
    ANIMATION_ACTION_COVER_CROUCH_READY_RIGHT_FIRE = 0x1CB,
    ANIMATION_ACTION_COVER_CROUCH_BLIND_LEFT_FIRE = 0x1CC,
    ANIMATION_ACTION_COVER_CROUCH_BLIND_RIGHT_FIRE = 0x1CD,
    ANIMATION_ACTION_COVER_CROUCH_BLIND_LEFT_WALK_FIRE = 0x1CE,
    ANIMATION_ACTION_COVER_CROUCH_BLIND_RIGHT_WALK_FIRE = 0x1CF,
    ANIMATION_ACTION_COVER_STAND_EXIT_LEFT = 0x1D0,
    ANIMATION_ACTION_COVER_STAND_EXIT_RIGHT = 0x1D1,
    ANIMATION_ACTION_COVER_CROUCH_EXIT_LEFT = 0x1D2,
    ANIMATION_ACTION_COVER_CROUCH_EXIT_RIGHT = 0x1D3,
    ANIMATION_ACTION_COVER_CROUCH_EXIT_DIVE = 0x1D4,
    ANIMATION_ACTION_COVER_CROUCH_EXIT_DIVE_LEFT = 0x1D5,
    ANIMATION_ACTION_FLINCH_FACE = 0x1D6,
    ANIMATION_ACTION_FLINCH_HEAD_FORWARD = 0x1D7,
    ANIMATION_ACTION_FLINCH_HEAD_BACKWARD = 0x1D8,
    ANIMATION_ACTION_FLINCH_HEAD_RIGHT = 0x1D9,
    ANIMATION_ACTION_FLINCH_HEAD_LEFT = 0x1DA,
    ANIMATION_ACTION_FLINCH_TORSO_FORWARD = 0x1DB,
    ANIMATION_ACTION_FLINCH_TORSO_BACKWARD = 0x1DC,
    ANIMATION_ACTION_FLINCH_TORSO_RIGHT = 0x1DD,
    ANIMATION_ACTION_FLINCH_TORSO_LEFT = 0x1DE,
    ANIMATION_ACTION_FLINCH_PELVIS_FORWARD = 0x1DF,
    ANIMATION_ACTION_FLINCH_PELVIS_BACKWARD = 0x1E0,
    ANIMATION_ACTION_FLINCH_PELVIS_RIGHT = 0x1E1,
    ANIMATION_ACTION_FLINCH_PELVIS_LEFT = 0x1E2,
    ANIMATION_ACTION_FLINCH_BODY = 0x1E3,
    ANIMATION_ACTION_FLINCH_SLIGHT_HEAD_FORWARD = 0x1E4,
    ANIMATION_ACTION_FLINCH_SLIGHT_HEAD_BACKWARD = 0x1E5,
    ANIMATION_ACTION_FLINCH_SLIGHT_HEAD_RIGHT = 0x1E6,
    ANIMATION_ACTION_FLINCH_SLIGHT_HEAD_LEFT = 0x1E7,
    ANIMATION_ACTION_FLINCH_SLIGHT_TORSO_FORWARD = 0x1E8,
    ANIMATION_ACTION_FLINCH_SLIGHT_TORSO_BACKWARD = 0x1E9,
    ANIMATION_ACTION_FLINCH_SLIGHT_TORSO_RIGHT = 0x1EA,
    ANIMATION_ACTION_FLINCH_SLIGHT_TORSO_LEFT = 0x1EB,
    ANIMATION_ACTION_FLINCH_SLIGHT_PELVIS_FORWARD = 0x1EC,
    ANIMATION_ACTION_FLINCH_SLIGHT_PELVIS_BACKWARD = 0x1ED,
    ANIMATION_ACTION_FLINCH_SLIGHT_PELVIS_RIGHT = 0x1EE,
    ANIMATION_ACTION_FLINCH_SLIGHT_PELVIS_LEFT = 0x1EF,
    ANIMATION_ACTION_FLINCH_SLIGHT_CROUCH_FORWARD = 0x1F0,
    ANIMATION_ACTION_FLINCH_SLIGHT_CROUCH_BACKWARD = 0x1F1,
    ANIMATION_ACTION_FLINCH_SLIGHT_CROUCH_RIGHT = 0x1F2,
    ANIMATION_ACTION_FLINCH_SLIGHT_CROUCH_LEFT = 0x1F3,
    ANIMATION_ACTION_NONCOMBAT_FLINCH_PELVIS_FORWARD = 0x1F4,
    ANIMATION_ACTION_NONCOMBAT_FLINCH_PELVIS_BACK = 0x1F5,
    ANIMATION_ACTION_NONCOMBAT_FLINCH_PELVIS_RIGHT = 0x1F6,
    ANIMATION_ACTION_NONCOMBAT_FLINCH_PELVIS_LEFT = 0x1F7,
    ANIMATION_ACTION_NONCOMBAT_FLINCH_TORSO_FORWARD = 0x1F8,
    ANIMATION_ACTION_NONCOMBAT_FLINCH_TORSO_BACK = 0x1F9,
    ANIMATION_ACTION_NONCOMBAT_FLINCH_TORSO_RIGHT = 0x1FA,
    ANIMATION_ACTION_NONCOMBAT_FLINCH_TORSO_LEFT = 0x1FB,
    ANIMATION_ACTION_EQUIP = 0x1FC,
    ANIMATION_ACTION_UNEQUIP = 0x1FD,
    ANIMATION_ACTION_MOVE_EQUIP = 0x1FE,
    ANIMATION_ACTION_MOVE_UNEQUIP = 0x1FF,
    ANIMATION_ACTION_CROUCH_EQUIP = 0x200,
    ANIMATION_ACTION_CROUCH_UNEQUIP = 0x201,
    ANIMATION_ACTION_CROUCH_MOVE_EQUIP = 0x202,
    ANIMATION_ACTION_CROUCH_MOVE_UNEQUIP = 0x203,
    ANIMATION_ACTION_COVER_CROUCH_EQUIP_LEFT = 0x204,
    ANIMATION_ACTION_COVER_CROUCH_EQUIP_RIGHT = 0x205,
    ANIMATION_ACTION_COVER_STAND_EQUIP_LEFT = 0x206,
    ANIMATION_ACTION_COVER_STAND_EQUIP_RIGHT = 0x207,
    ANIMATION_ACTION_LOOK_LEFT = 0x208,
    ANIMATION_ACTION_LOOK_RIGHT = 0x209,
    ANIMATION_ACTION_RELOAD = 0x20A,
    ANIMATION_ACTION_WALK_RELOAD = 0x20B,
    ANIMATION_ACTION_RUN_RELOAD = 0x20C,
    ANIMATION_ACTION_CROUCH_RELOAD = 0x20D,
    ANIMATION_ACTION_CROUCH_WALK_RELOAD = 0x20E,
    ANIMATION_ACTION_VEHICLE_RELOAD = 0x20F,
    ANIMATION_ACTION_PASSENGER_RELOAD = 0x210,
    ANIMATION_ACTION_DPASSENGER_RELOAD = 0x211,
    ANIMATION_ACTION_COVER_STAND_RELOAD_LEFT = 0x212,
    ANIMATION_ACTION_COVER_CROUCH_RELOAD_LEFT = 0x213,
    ANIMATION_ACTION_COVER_STAND_RELOAD_RIGHT = 0x214,
    ANIMATION_ACTION_COVER_CROUCH_RELOAD_RIGHT = 0x215,
    ANIMATION_ACTION_MELEE = 0x216,
    ANIMATION_ACTION_MELEE2 = 0x217,
    ANIMATION_ACTION_MELEE3 = 0x218,
    ANIMATION_ACTION_MELEE4 = 0x219,
    ANIMATION_ACTION_MELEE_MOVING = 0x21A,
    ANIMATION_ACTION_MELEE_AIR = 0x21B,
    ANIMATION_ACTION_CROUCH_MELEE = 0x21C,
    ANIMATION_ACTION_CROUCH_MELEE_MOVING = 0x21D,
    ANIMATION_ACTION_MELEE_FAST = 0x21E,
    ANIMATION_ACTION_MELEE_FAST_FAST = 0x21F,
    ANIMATION_ACTION_MELEE_FAST_FAST_FAST = 0x220,
    ANIMATION_ACTION_MELEE_FAST_FAST_SLOW = 0x221,
    ANIMATION_ACTION_MELEE_FAST_SLOW = 0x222,
    ANIMATION_ACTION_MELEE_FAST_SLOW_FAST = 0x223,
    ANIMATION_ACTION_MELEE_FAST_SLOW_SLOW = 0x224,
    ANIMATION_ACTION_MELEE_SLOW = 0x225,
    ANIMATION_ACTION_MELEE_SLOW_FAST = 0x226,
    ANIMATION_ACTION_MELEE_SLOW_FAST_FAST = 0x227,
    ANIMATION_ACTION_MELEE_SLOW_FAST_SLOW = 0x228,
    ANIMATION_ACTION_MELEE_SLOW_SLOW = 0x229,
    ANIMATION_ACTION_MELEE_SLOW_SLOW_FAST = 0x22A,
    ANIMATION_ACTION_MELEE_SLOW_SLOW_SLOW = 0x22B,
    ANIMATION_ACTION_BLOCK_FLINCH_HIGH = 0x22C,
    ANIMATION_ACTION_BLOCK_FLINCH_LOW = 0x22D,
    ANIMATION_ACTION_BK_FALLDOWN = 0x22E,
    ANIMATION_ACTION_BK_GETUP = 0x22F,
    ANIMATION_ACTION_FW_FALLDOWN = 0x230,
    ANIMATION_ACTION_FW_GETUP = 0x231,
    ANIMATION_ACTION_FALLDOWN_BEHIND = 0x232,
    ANIMATION_ACTION_FW_NUDGE_BY_CAR = 0x233,
    ANIMATION_ACTION_IMPACT_FROM_FRONT = 0x234,
    ANIMATION_ACTION_IMPACT_FROM_BACK = 0x235,
    ANIMATION_ACTION_COMBAT_TO_STAND = 0x236,
    ANIMATION_ACTION_DIVE_FOR_COVER = 0x237,
    ANIMATION_ACTION_STAND_GO_PRONE = 0x238,
    ANIMATION_ACTION_KNEEL_GO_PRONE = 0x239,
    ANIMATION_ACTION_PRONE_TO_KNEEL = 0x23A,
    ANIMATION_ACTION_SCRAMBLE_TO_FEET = 0x23B,
    ANIMATION_ACTION_DEATH = 0x23C,
    ANIMATION_ACTION_DEATH_PELVIS_FORWARD = 0x23D,
    ANIMATION_ACTION_DEATH_PELVIS_BACK = 0x23E,
    ANIMATION_ACTION_DEATH_PELVIS_LEFT = 0x23F,
    ANIMATION_ACTION_DEATH_PELVIS_RIGHT = 0x240,
    ANIMATION_ACTION_DEATH_TORSO_FORWARD = 0x241,
    ANIMATION_ACTION_DEATH_TORSO_BACK = 0x242,
    ANIMATION_ACTION_DEATH_TORSO_LEFT = 0x243,
    ANIMATION_ACTION_DEATH_TORSO_RIGHT = 0x244,
    ANIMATION_ACTION_DEATH_HEAD_FORWARD = 0x245,
    ANIMATION_ACTION_DEATH_HEAD_BACK = 0x246,
    ANIMATION_ACTION_DEATH_HEAD_LEFT = 0x247,
    ANIMATION_ACTION_DEATH_HEAD_RIGHT = 0x248,
    ANIMATION_ACTION_CROUCH_DEATH_PELVIS_FORWARD = 0x249,
    ANIMATION_ACTION_CROUCH_DEATH_PELVIS_BACK = 0x24A,
    ANIMATION_ACTION_CROUCH_DEATH_PELVIS_LEFT = 0x24B,
    ANIMATION_ACTION_CROUCH_DEATH_PELVIS_RIGHT = 0x24C,
    ANIMATION_ACTION_CROUCH_DEATH_TORSO_FORWARD = 0x24D,
    ANIMATION_ACTION_CROUCH_DEATH_TORSO_BACK = 0x24E,
    ANIMATION_ACTION_CROUCH_DEATH_TORSO_LEFT = 0x24F,
    ANIMATION_ACTION_CROUCH_DEATH_TORSO_RIGHT = 0x250,
    ANIMATION_ACTION_CROUCH_DEATH_HEAD_FORWARD = 0x251,
    ANIMATION_ACTION_CROUCH_DEATH_HEAD_BACK = 0x252,
    ANIMATION_ACTION_CROUCH_DEATH_HEAD_LEFT = 0x253,
    ANIMATION_ACTION_CROUCH_DEATH_HEAD_RIGHT = 0x254,
    ANIMATION_ACTION_READY_FLINCH_FACE = 0x255,
    ANIMATION_ACTION_READY_FLINCH_MID = 0x256,
    ANIMATION_ACTION_STAND_FLINCH_FACE = 0x257,
    ANIMATION_ACTION_STAND_FLINCH_MID = 0x258,
    ANIMATION_ACTION_CROUCH_FLINCH_BODY = 0x259,
    ANIMATION_ACTION_STUNGUN_FLINCH = 0x25A,
    ANIMATION_ACTION_EXPLOSION_FLINCH_FRONT = 0x25B,
    ANIMATION_ACTION_EXPLOSION_FLINCH_BACK = 0x25C,
    ANIMATION_ACTION_EXPLOSION_FLINCH_LEFT = 0x25D,
    ANIMATION_ACTION_EXPLOSION_FLINCH_RIGHT = 0x25E,
    ANIMATION_ACTION_EXPLOSION_STUMBLE_FRONT = 0x25F,
    ANIMATION_ACTION_EXPLOSION_STUMBLE_BACK = 0x260,
    ANIMATION_ACTION_EXPLOSION_STUMBLE_LEFT = 0x261,
    ANIMATION_ACTION_EXPLOSION_STUMBLE_RIGHT = 0x262,
    ANIMATION_ACTION_EXPLOSION_DUCK_FRONT = 0x263,
    ANIMATION_ACTION_EXPLOSION_DUCK_BACK = 0x264,
    ANIMATION_ACTION_EXPLOSION_DUCK_LEFT = 0x265,
    ANIMATION_ACTION_EXPLOSION_DUCK_RIGHT = 0x266,
    ANIMATION_ACTION_EXPLOSION_KNOCKDOWN_FRONT = 0x267,
    ANIMATION_ACTION_EXPLOSION_KNOCKDOWN_BACK = 0x268,
    ANIMATION_ACTION_EXPLOSION_KNOCKDOWN_LEFT = 0x269,
    ANIMATION_ACTION_EXPLOSION_KNOCKDOWN_RIGHT = 0x26A,
    ANIMATION_ACTION_CROUCH_FLINCH_FRONT = 0x26B,
    ANIMATION_ACTION_CROUCH_FLINCH_BACK = 0x26C,
    ANIMATION_ACTION_CROUCH_FLINCH_LEFT = 0x26D,
    ANIMATION_ACTION_CROUCH_FLINCH_RIGHT = 0x26E,
    ANIMATION_ACTION_TOSS_ITEM = 0x26F,
    ANIMATION_ACTION_THROW_ITEM = 0x270,
    ANIMATION_ACTION_PLACE_ITEM = 0x271,
    ANIMATION_ACTION_PLANT_BOMB = 0x272,
    ANIMATION_ACTION_THROW_ITEM_DRIVE = 0x273,
    ANIMATION_ACTION_THROW_ITEM_DRIVE_LEFT = 0x274,
    ANIMATION_ACTION_THROW_ITEM_DRIVE_RIGHT = 0x275,
    ANIMATION_ACTION_THROW_ITEM_MOVE_FORWARD = 0x276,
    ANIMATION_ACTION_THROW_ITEM_MOVE_BACK = 0x277,
    ANIMATION_ACTION_THROW_ITEM_MOVE_LEFT = 0x278,
    ANIMATION_ACTION_THROW_ITEM_MOVE_RIGHT = 0x279,
    ANIMATION_ACTION_THROW_CROUCH = 0x27A,
    ANIMATION_ACTION_THROW_GRENADE = 0x27B,
    ANIMATION_ACTION_ROLL_GRENADE = 0x27C,
    ANIMATION_ACTION_COVER_CROUCH_RIGHT_THROW_GRENADE = 0x27D,
    ANIMATION_ACTION_COVER_CROUCH_LEFT_THROW_GRENADE = 0x27E,
    ANIMATION_ACTION_COVER_STAND_RIGHT_THROW_GRENADE = 0x27F,
    ANIMATION_ACTION_COVER_STAND_LEFT_THROW_GRENADE = 0x280,
    ANIMATION_ACTION_LOOK_AROUND = 0x281,
    ANIMATION_ACTION_POINT_LEFT = 0x282,
    ANIMATION_ACTION_POINT_RIGHT = 0x283,
    ANIMATION_ACTION_POINT_AHEAD = 0x284,
    ANIMATION_ACTION_BATTLE_CRY = 0x285,
    ANIMATION_ACTION_COMBAT_CHEER = 0x286,
    ANIMATION_ACTION_COMBAT_RUN_CHEER = 0x287,
    ANIMATION_ACTION_TAUNT = 0x288,
    ANIMATION_ACTION_TAUNT_ALT = 0x289,
    ANIMATION_ACTION_WALKING_TAUNT = 0x28A,
    ANIMATION_ACTION_TALK_YELL = 0x28B,
    ANIMATION_ACTION_MOTION_TO_MOVE = 0x28C,
    ANIMATION_ACTION_SHOVE_CIVILIAN = 0x28D,
    ANIMATION_ACTION_BEAT_CIVILIAN = 0x28E,
    ANIMATION_ACTION_STOMP = 0x28F,
    ANIMATION_ACTION_KICK = 0x290,
    ANIMATION_ACTION_CHECK_ID = 0x291,
    ANIMATION_ACTION_CHECK_ID_APPROVED = 0x292,
    ANIMATION_ACTION_CHECK_ID_DENIED = 0x293,
    ANIMATION_ACTION_REACT_ANGRY_A = 0x294,
    ANIMATION_ACTION_REACT_ANGRY_B = 0x295,
    ANIMATION_ACTION_REACT_ANGRY_C = 0x296,
    ANIMATION_ACTION_REACT_ANGRY_D = 0x297,
    ANIMATION_ACTION_REACT_SHOVED = 0x298,
    ANIMATION_ACTION_REACT_SURPRISED = 0x299,
    ANIMATION_ACTION_GIVE_ID = 0x29A,
    ANIMATION_ACTION_GIVE_ID_APPROVED = 0x29B,
    ANIMATION_ACTION_GIVE_ID_DENIED = 0x29C,
    ANIMATION_ACTION_START_TURN_LEFT = 0x29D,
    ANIMATION_ACTION_START_TURN_RIGHT = 0x29E,
    ANIMATION_ACTION_END_TURN_LEFT = 0x29F,
    ANIMATION_ACTION_END_TURN_RIGHT = 0x2A0,
    ANIMATION_ACTION_PISTOL_END_TURN_LEFT = 0x2A1,
    ANIMATION_ACTION_PISTOL_END_TURN_RIGHT = 0x2A2,
    ANIMATION_ACTION_MORPH1 = 0x2A3,
    ANIMATION_ACTION_CUSTOM = 0x2A4,
    ANIMATION_ACTION_FLINCH_TEST = 0x2A5,
    ANIMATION_ACTION_TAG = 0x2A6,
    ANIMATION_ACTION_WALK_STOP = 0x2A7,
    ANIMATION_ACTION_STAND_TURN = 0x2A8,
    ANIMATION_ACTION_RUN_STOP = 0x2A9,
    ANIMATION_ACTION_RUNNING_TURN = 0x2AA,
    ANIMATION_ACTION_RUNNING_TURN_RIGHT = 0x2AB,
    ANIMATION_ACTION_RUNNING_TURN_LEFT = 0x2AC,
    ANIMATION_ACTION_RUNNING_TURN_BACK = 0x2AD,
    ANIMATION_ACTION_RUN_BACK_TO_LEFT = 0x2AE,
    ANIMATION_ACTION_RUN_LEFT_TO_BACK = 0x2AF,
    ANIMATION_ACTION_COVER_INTO_STAND_LEFT = 0x2B0,
    ANIMATION_ACTION_COVER_INTO_STAND_RIGHT = 0x2B1,
    ANIMATION_ACTION_COVER_INTO_CROUCH_LEFT = 0x2B2,
    ANIMATION_ACTION_COVER_INTO_CROUCH_RIGHT = 0x2B3,
    ANIMATION_ACTION_COVER_INTO_STAND_LEFT_SIDE = 0x2B4,
    ANIMATION_ACTION_COVER_INTO_STAND_RIGHT_SIDE = 0x2B5,
    ANIMATION_ACTION_COVER_INTO_CROUCH_LEFT_SIDE = 0x2B6,
    ANIMATION_ACTION_COVER_INTO_CROUCH_RIGHT_SIDE = 0x2B7,
    ANIMATION_ACTION_COVER_STAND_LEFT_LEAN_OUT = 0x2B8,
    ANIMATION_ACTION_COVER_STAND_LEFT_LEAN_IN = 0x2B9,
    ANIMATION_ACTION_COVER_STAND_LEFT_STEP_OUT = 0x2BA,
    ANIMATION_ACTION_COVER_STAND_LEFT_STEP_IN = 0x2BB,
    ANIMATION_ACTION_COVER_STAND_RIGHT_LEAN_OUT = 0x2BC,
    ANIMATION_ACTION_COVER_STAND_RIGHT_LEAN_IN = 0x2BD,
    ANIMATION_ACTION_COVER_STAND_RIGHT_STEP_OUT = 0x2BE,
    ANIMATION_ACTION_COVER_STAND_RIGHT_STEP_IN = 0x2BF,
    ANIMATION_ACTION_COVER_CROUCH_LEFT_LEAN_OUT = 0x2C0,
    ANIMATION_ACTION_COVER_CROUCH_LEFT_LEAN_IN = 0x2C1,
    ANIMATION_ACTION_COVER_CROUCH_LEFT_STEP_OUT = 0x2C2,
    ANIMATION_ACTION_COVER_CROUCH_LEFT_STEP_IN = 0x2C3,
    ANIMATION_ACTION_COVER_CROUCH_RIGHT_LEAN_OUT = 0x2C4,
    ANIMATION_ACTION_COVER_CROUCH_RIGHT_LEAN_IN = 0x2C5,
    ANIMATION_ACTION_COVER_CROUCH_RIGHT_STEP_OUT = 0x2C6,
    ANIMATION_ACTION_COVER_CROUCH_RIGHT_STEP_IN = 0x2C7,
    ANIMATION_ACTION_OPEN_DOOR_INSIDE_1 = 0x2C8,
    ANIMATION_ACTION_OPEN_DOOR_INSIDE_2 = 0x2C9,
    ANIMATION_ACTION_OPEN_DOOR_INSIDE_3 = 0x2CA,
    ANIMATION_ACTION_OPEN_DOOR_OUTSIDE_1 = 0x2CB,
    ANIMATION_ACTION_OPEN_DOOR_OUTSIDE_2 = 0x2CC,
    ANIMATION_ACTION_OPEN_DOOR_OUTSIDE_3 = 0x2CD,
    ANIMATION_ACTION_OPEN_DOOR_OUTSIDE_4 = 0x2CE,
    ANIMATION_ACTION_CLOSE_DOOR_INSIDE_1 = 0x2CF,
    ANIMATION_ACTION_CLOSE_DOOR_INSIDE_2 = 0x2D0,
    ANIMATION_ACTION_CLOSE_DOOR_INSIDE_3 = 0x2D1,
    ANIMATION_ACTION_CLOSE_DOOR_INSIDE_4 = 0x2D2,
    ANIMATION_ACTION_CLOSE_DOOR_OUTSIDE_1 = 0x2D3,
    ANIMATION_ACTION_CLOSE_DOOR_OUTSIDE_2 = 0x2D4,
    ANIMATION_ACTION_CLOSE_DOOR_OUTSIDE_3 = 0x2D5,
    ANIMATION_ACTION_EXIT_DRIVER = 0x2D6,
    ANIMATION_ACTION_EXIT_REAR_DRIVER = 0x2D7,
    ANIMATION_ACTION_EXIT_PASS_1 = 0x2D8,
    ANIMATION_ACTION_EXIT_PASS_2 = 0x2D9,
    ANIMATION_ACTION_EXIT_PASS_3 = 0x2DA,
    ANIMATION_ACTION_EXIT_PASS_4 = 0x2DB,
    ANIMATION_ACTION_EXIT_PASS_5 = 0x2DC,
    ANIMATION_ACTION_EXIT_PASS_6 = 0x2DD,
    ANIMATION_ACTION_EXIT_PASS_7 = 0x2DE,
    ANIMATION_ACTION_DIVE_DRIVER = 0x2DF,
    ANIMATION_ACTION_DIVE_PASS = 0x2E0,
    ANIMATION_ACTION_EXIT_MAIN = 0x2E1,
    ANIMATION_ACTION_EXIT_DRIVER_QUICK = 0x2E2,
    ANIMATION_ACTION_EXIT_DRIVER_QUICK_REVERSE = 0x2E3,
    ANIMATION_ACTION_EXIT_DRIVER_DR_SIDE = 0x2E4,
    ANIMATION_ACTION_EXIT_DRIVER_PS_SIDE = 0x2E5,
    ANIMATION_ACTION_EXIT_PASS_1_QUICK = 0x2E6,
    ANIMATION_ACTION_EXIT_PASS_1_QUICK_REVERSE = 0x2E7,
    ANIMATION_ACTION_EXIT_PASS_1_DIVE = 0x2E8,
    ANIMATION_ACTION_EXIT_PASS_1_DR_SIDE = 0x2E9,
    ANIMATION_ACTION_EXIT_PASS_1_PS_SIDE = 0x2EA,
    ANIMATION_ACTION_EXIT_PASS_2_QUICK = 0x2EB,
    ANIMATION_ACTION_EXIT_PASS_2_QUICK_REVERSE = 0x2EC,
    ANIMATION_ACTION_EXIT_PASS_2_DIVE = 0x2ED,
    ANIMATION_ACTION_EXIT_PASS_3_QUICK = 0x2EE,
    ANIMATION_ACTION_EXIT_PASS_3_QUICK_REVERSE = 0x2EF,
    ANIMATION_ACTION_EXIT_PASS_3_DIVE = 0x2F0,
    ANIMATION_ACTION_EXIT_FLIP = 0x2F1,
    ANIMATION_ACTION_PULLED_OUT_DRIVER_NORMAL = 0x2F2,
    ANIMATION_ACTION_PULLED_OUT_DRIVER_BASH = 0x2F3,
    ANIMATION_ACTION_PULLED_OUT_DRIVER_PUNCH = 0x2F4,
    ANIMATION_ACTION_PULLED_OUT_REAR_DRIVER_NORMAL = 0x2F5,
    ANIMATION_ACTION_PULLED_OUT_REAR_DRIVER_BASH = 0x2F6,
    ANIMATION_ACTION_PULLED_OUT_REAR_DRIVER_PUNCH = 0x2F7,
    ANIMATION_ACTION_PULLED_OUT_PASS_NORMAL = 0x2F8,
    ANIMATION_ACTION_PULLED_OUT_PASS_BASH = 0x2F9,
    ANIMATION_ACTION_PULLED_OUT_PASS_PUNCH = 0x2FA,
    ANIMATION_ACTION_ENTER_PRIMARY_1 = 0x2FB,
    ANIMATION_ACTION_ENTER_PRIMARY_2 = 0x2FC,
    ANIMATION_ACTION_ENTER_PRIMARY_3 = 0x2FD,
    ANIMATION_ACTION_ENTER_SECONDARY_1 = 0x2FE,
    ANIMATION_ACTION_ENTER_SECONDARY_2 = 0x2FF,
    ANIMATION_ACTION_ENTER_SECONDARY_3 = 0x300,
    ANIMATION_ACTION_ENTER_TERTIARY_1 = 0x301,
    ANIMATION_ACTION_ENTER_TERTIARY_2 = 0x302,
    ANIMATION_ACTION_ENTER_TERTIARY_3 = 0x303,
    ANIMATION_ACTION_ENTER_PASS_1 = 0x304,
    ANIMATION_ACTION_ENTER_PASS_2 = 0x305,
    ANIMATION_ACTION_ENTER_PASS_3 = 0x306,
    ANIMATION_ACTION_ENTER_PASS_4 = 0x307,
    ANIMATION_ACTION_ENTER_PASS_5 = 0x308,
    ANIMATION_ACTION_ENTER_PASS_6 = 0x309,
    ANIMATION_ACTION_ENTER_PASS_7 = 0x30A,
    ANIMATION_ACTION_PULLOUT_DRIVER_NORMAL = 0x30B,
    ANIMATION_ACTION_PULLOUT_DRIVER_BASH = 0x30C,
    ANIMATION_ACTION_PULLOUT_DRIVER_PUNCH = 0x30D,
    ANIMATION_ACTION_PULLOUT_REAR_DRIVER_NORMAL = 0x30E,
    ANIMATION_ACTION_PULLOUT_REAR_DRIVER_BASH = 0x30F,
    ANIMATION_ACTION_PULLOUT_REAR_DRIVER_PUNCH = 0x310,
    ANIMATION_ACTION_PULLOUT_PASS_NORMAL = 0x311,
    ANIMATION_ACTION_PULLOUT_PASS_BASH = 0x312,
    ANIMATION_ACTION_PULLOUT_PASS_PUNCH = 0x313,
    ANIMATION_ACTION_SLIDE_DRIVER_TO_PASS = 0x314,
    ANIMATION_ACTION_SLIDE_PASS_TO_DRIVER = 0x315,
    ANIMATION_ACTION_WALKER_MOUNT = 0x316,
    ANIMATION_ACTION_LADDER_ENTER_A = 0x317,
    ANIMATION_ACTION_LADDER_ENTER_B = 0x318,
    ANIMATION_ACTION_LADDER_ENTER_C = 0x319,
    ANIMATION_ACTION_LADDER_ENTER_TOP = 0x31A,
    ANIMATION_ACTION_LADDER_AIR_GRAB_FRONT = 0x31B,
    ANIMATION_ACTION_LADDER_AIR_GRAB_LEFT = 0x31C,
    ANIMATION_ACTION_LADDER_AIR_GRAB_RIGHT = 0x31D,
    ANIMATION_ACTION_LADDER_AIR_GRAB_FRONT_LEFT = 0x31E,
    ANIMATION_ACTION_LADDER_AIR_GRAB_FRONT_RIGHT = 0x31F,
    ANIMATION_ACTION_LADDER_EXIT_BOTTOM = 0x320,
    ANIMATION_ACTION_LADDER_EXIT_TOP_LEFT = 0x321,
    ANIMATION_ACTION_LADDER_EXIT_TOP_RIGHT = 0x322,
    ANIMATION_ACTION_LADDER_CLIMB_LEFT = 0x323,
    ANIMATION_ACTION_LADDER_CLIMB_RIGHT = 0x324,
    ANIMATION_ACTION_LADDER_SLIDE_STOP = 0x325,
    ANIMATION_ACTION_LADDER_SLIDE_START_LEFT = 0x326,
    ANIMATION_ACTION_LADDER_SLIDE_START_RIGHT = 0x327,
    ANIMATION_ACTION_LADDER_JUMP_LEFT = 0x328,
    ANIMATION_ACTION_LADDER_JUMP_RIGHT = 0x329,
    ANIMATION_ACTION_FINE_AIM_IN = 0x32A,
    ANIMATION_ACTION_FINE_AIM_OUT = 0x32B,
    ANIMATION_ACTION_FINE_AIM_FIRE = 0x32C,
    ANIMATION_ACTION_FINE_AIM_FIRE_BACK = 0x32D,
    ANIMATION_ACTION_FINE_AIM_FIRE_LEFT = 0x32E,
    ANIMATION_ACTION_FINE_AIM_FIRE_RIGHT = 0x32F,
    ANIMATION_ACTION_FINE_AIM_CROUCH_FIRE = 0x330,
    ANIMATION_ACTION_FINE_AIM_CROUCH_FIRE_BACK = 0x331,
    ANIMATION_ACTION_FINE_AIM_CROUCH_FIRE_LEFT = 0x332,
    ANIMATION_ACTION_FINE_AIM_CROUCH_FIRE_RIGHT = 0x333,
    ANIMATION_ACTION_STAND_PEEING = 0x334,
    ANIMATION_ACTION_STAND_USE_COMPUTER = 0x335,
    ANIMATION_ACTION_STAND_SCAN_HORIZON = 0x336,
    ANIMATION_ACTION_STAND_TO_LEAN = 0x337,
    ANIMATION_ACTION_LEAN_TO_STAND = 0x338,
    AMIMATION_ACTION_OPEN_MEDICAL_SUPPLIES = 0x339,
    ANIMATION_ACTION_OPEN_FILE_CABINET = 0x33A,
    ANIMATION_ACTION_JACKHAMMER_USE = 0x33B,
    ANIMATION_ACTION_JACKHAMMER_EXIT = 0x33C,
    ANIMATION_ACTION_STAND_WEAPON_IDLE = 0x33D,
    ANIMATION_ACTION_STAND_WEAPON_IDLE_A = 0x33E,
    ANIMATION_ACTION_COUGH = 0x33F,
    ANIMATION_ACTION_RADIO_CHECK_IN = 0x340,
    ANIMATION_ACTION_RADIO_ENTER = 0x341,
    ANIMATION_ACTION_SALUTE = 0x342,
    ANIMATION_ACTION_CHEER_A = 0x343,
    ANIMATION_ACTION_OPEN_AMMO_BOX = 0x344,
    ANIMATION_ACTION_OPEN_WEAPON_LOCKER = 0x345,
    ANIMATION_ACTION_CLOSE_WEAPON_LOCKER = 0x346,
    ANIMATION_ACTION_FREE_PRISONER = 0x347,
    ANIMATION_ACTION_FREE_PRISONER_MISSION = 0x348,
    ANIMATION_ACTION_KNEEL_TO_STAND_HANDS_TIED = 0x349,
    ANIMATION_ACTION_STAND_FREE_HANDS = 0x34A,
    ANIMATION_ACTION_GREET_DISMISS = 0x34B,
    ANIMATION_ACTION_GREET_DISMISS_LEFT = 0x34C,
    ANIMATION_ACTION_GREET_DISMISS_RIGHT = 0x34D,
    ANIMATION_ACTION_CHECK_WATCH = 0x34E,
    ANIMATION_ACTION_PARANOID_GLANCE = 0x34F,
    ANIMATION_ACTION_SCRATCH_HEAD = 0x350,
    ANIMATION_ACTION_STAND_WEIGHT_SHIFT = 0x351,
    ANIMATION_ACTION_FLYER_TAKEOFF = 0x352,
    ANIMATION_ACTION_FLYER_LAND = 0x353,
    ANIMATION_ACTION_SABOTAGE_FLYER = 0x354,
    ANIMATION_ACTION_DANS_DEATH = 0x355,
    ANIMATION_ACTION_SIT_TO_STAND_BENCH = 0x356,
    ANIMATION_ACTION_SIT_TO_STAND_BENCH_TIRED = 0x357,
    ANIMATION_ACTION_SIT_TO_STAND_BENCH_READ = 0x358,
    ANIMATION_ACTION_SIT_TO_STAND_BENCH_FAST = 0x359,
    ANIMATION_ACTION_STAND_TO_SIT_ANGRY = 0x35A,
    ANIMATION_ACTION_STAND_TO_SIT_BENCH = 0x35B,
    ANIMATION_ACTION_STAND_TO_SIT_BENCH_TIRED = 0x35C,
    ANIMATION_ACTION_STAND_TO_SIT_BENCH_READ = 0x35D,
    ANIMATION_ACTION_STAND_B_IDLE = 0x35E,
    ANIMATION_ACTION_PICKUP_BEAM = 0x35F,
    ANIMATION_ACTION_DROP_BEAM = 0x360,
    ANIMATION_ACTION_DROP_BEAM_QUICK = 0x361,
    ANIMATION_ACTION_BEER_DROP = 0x362,
    ANIMATION_ACTION_BAR_CLEAN_ENTER_A = 0x363,
    ANIMATION_ACTION_BAR_CLEAN_EXIT_A = 0x364,
    ANIMATION_ACTION_BEER_SIT_DRINK = 0x365,
    ANIMATION_ACTION_BEER_STAND_DRINK = 0x366,
    ANIMATION_ACTION_BAR_LEAN_TALK = 0x367,
    ANIMATION_ACTION_BEER_TO_STAND = 0x368,
    ANIMATION_ACTION_TALK_SHORT = 0x369,
    ANIMATION_ACTION_TALK_LONG = 0x36A,
    ANIMATION_ACTION_BEER_TALK = 0x36B,
    ANIMATION_ACTION_MINING_GROUND_ENTER = 0x36C,
    ANIMATION_ACTION_MINING_GROUND_EXIT = 0x36D,
    ANIMATION_ACTION_CLIPBOARD_POINT = 0x36E,
    ANIMATION_ACTION_CLIPBOARD_READ = 0x36F,
    ANIMATION_ACTION_STOREKEEPER_SELL = 0x370,
    ANIMATION_ACTION_STOREKEEPER_THINK = 0x371,
    ANIMATION_ACTION_ROCK_PICKUP = 0x372,
    ANIMATION_ACTION_ROCK_TOSS = 0x373,
    ANIMATION_ACTION_ROCK_QUICK_DROP = 0x374,
    ANIMATION_ACTION_XRAY_STAND_LOOK = 0x375,
    ANIMATION_ACTION_READ_SIGN = 0x376,
    ANIMATION_ACTION_AMBIENT_STAND_TO_CROUCH = 0x377,
    ANIMATION_ACTION_AMBIENT_CROUCH_TO_STAND = 0x378,
    ANIMATION_ACTION_GIVE = 0x379,
    ANIMATION_ACTION_SPRAY = 0x37A,
    ANIMATION_ACTION_CROUCH_SURVEY = 0x37B,
    ANIMATION_ACTION_STAND_SURVEY = 0x37C,
    ANIMATION_ACTION_CAR_INSPECT = 0x37D,
    ANIMATION_ACTION_BRIEFCASE_COMPUTER_USE = 0x37E,
    ANIMATION_ACTION_CLUTTER_LABDESK = 0x37F,
    ANIMATION_ACTION_CROTCH_ADJUST = 0x380,
    ANIMATION_ACTION_TO_SIT_BENCHTABLE = 0x381,
    ANIMATION_ACTION_TO_SIT_BENCHTABLE_B = 0x382,
    ANIMATION_ACTION_TO_STAND_BENCHTABLE = 0x383,
    ANIMATION_ACTION_TO_STAND_BENCHTABLE_B = 0x384,
    ANIMATION_ACTION_SHOPPER_BROWSE = 0x385,
    ANIMATION_ACTION_SHOPPER_BROWSE_BAG = 0x386,
    ANIMATION_ACTION_SHOPPER_CHECK_OUT = 0x387,
    ANIMATION_ACTION_OPEN_LOCKER = 0x388,
    ANIMATION_ACTION_CLOSE_LOCKER = 0x389,
    ANIMATION_ACTION_GIVE_PISTOL = 0x38A,
    ANIMATION_ACTION_BOX_DROP = 0x38B,
    ANIMATION_ACTION_BOX_PICK_UP = 0x38C,
    ANIMATION_ACTION_LAY_IN_BED = 0x38D,
    ANIMATION_ACTION_STAND_FROM_BED = 0x38E,
    ANIMATION_ACTION_MINING_ENTER = 0x38F,
    ANIMATION_ACTION_MINING_EXIT = 0x390,
    ANIMATION_ACTION_BINOCULAR_ENTER = 0x391,
    ANIMATION_ACTION_BINOCULAR_EXIT = 0x392,
    ANIMATION_ACTION_GARDEN_TO_SIT = 0x393,
    ANIMATION_ACTION_GARDEN_TO_STAND = 0x394,
    ANIMATION_ACTION_HAMMER_ENTER = 0x395,
    ANIMATION_ACTION_LEAN_ENTER = 0x396,
    ANIMATION_ACTION_LEAN_ENTER_B = 0x397,
    ANIMATION_ACTION_STEPS_TO_SIT = 0x398,
    ANIMATION_ACTION_STEPS_TO_STAND = 0x399,
    ANIMATION_ACTION_SURFACE_KNOCK = 0x39A,
    ANIMATION_ACTION_WELD_ENTER = 0x39B,
    ANIMATION_ACTION_WELD_EXIT = 0x39C,
    ANIMATION_ACTION_WELD_USE = 0x39D,
    ANIMATION_ACTION_WELD_INSPECT = 0x39E,
    ANIMATION_ACTION_CROUCH_WELD_ENTER = 0x39F,
    ANIMATION_ACTION_CROUCH_WELD_EXIT = 0x3A0,
    ANIMATION_ACTION_CROUCH_WELD_USE = 0x3A1,
    ANIMATION_ACTION_CROUCH_WELD_INSPECT = 0x3A2,
    ANIMATION_ACTION_READ_METER = 0x3A3,
    ANIMATION_ACTION_READ_PIPE = 0x3A4,
    ANIMATION_ACTION_SECURITY_PANEL = 0x3A5,
    ANIMATION_ACTION_SECURITY_PANEL_A = 0x3A6,
    ANIMATION_ACTION_SECURITY_PANEL_HIGH = 0x3A7,
    ANIMATION_ACTION_SWEEP_ENTER = 0x3A8,
    ANIMATION_ACTION_SWEEP_EXIT = 0x3A9,
    ANIMATION_ACTION_SWEEP = 0x3AA,
    ANIMATION_ACTION_TOOLBOX_ENTER = 0x3AB,
    ANIMATION_ACTION_TOOLBOX_EXIT = 0x3AC,
    ANIMATION_ACTION_TOOLBOX_INSPECT = 0x3AD,
    ANIMATION_ACTION_SMOKE = 0x3AE,
    ANIMATION_ACTION_SMOKE_A = 0x3AF,
    ANIMATION_ACTION_SMOKE_B = 0x3B0,
    ANIMATION_ACTION_TIE_SHOE = 0x3B1,
    ANIMATION_ACTION_EXECUTE_FIRE = 0x3B2,
    ANIMATION_ACTION_COWER_DEATH = 0x3B3,
    AMIMATION_ACTION_COWER_TURN = 0x3B4,
    ANIMATION_ACTION_TAKE = 0x3B5,
    ANIMATION_ACTION_KNEEL_EXIT = 0x3B6,
    ANIMATION_ACTION_KNEEL_EXIT_A = 0x3B7,
    ANIMATION_ACTION_WORK_A = 0x3B8,
    ANIMATION_ACTION_WORK_B = 0x3B9,
    ANIMATION_ACTION_WORK_C = 0x3BA,
    ANIMATION_ACTION_INJURED_CROUCH = 0x3BB,
    ANIMATION_ACTION_INJURED_TO_STAND = 0x3BC,
    ANIMATION_ACTION_CLTR_EXC_ENTER = 0x3BD,
    ANIMATION_ACTION_CLTR_EXC_EXIT = 0x3BE,
    ANIMATION_ACTION_SAM_STAND_IDLE = 0x3BF,
    ANIMATION_ACTION_SAM_STAND_IDLE_A = 0x3C0,
    ANIMATION_ACTION_SAM_STAND_IDLE_B = 0x3C1,
    ANIMATION_ACTION_SAM_STAND_IDLE_C = 0x3C2,
    ANIMATION_ACTION_SAM_INSPECT_WEAPON = 0x3C3,
    ANIMATION_ACTION_SAM_INSPECT_ARC = 0x3C4,
    ANIMATION_ACTION_SAM_WELD_START = 0x3C5,
    ANIMATION_ACTION_SAM_WELD_END = 0x3C6,
    ANIMATION_ACTION_SAM_WELD_USE = 0x3C7,
    ANIMATION_ACTION_SAM_WELD_INSPECT = 0x3C8,
    ANIMATION_ACTION_SAM_PISTOL_POINT = 0x3C9,
    ANIMATION_ACTION_SAM_STAND_POINT = 0x3CA,
    ANIMATION_ACTION_RFC_IDLE_A = 0x3CB,
    ANIMATION_ACTION_RFC_IDLE_B = 0x3CC,
    ANIMATION_ACTION_OLD_COOT_TALK = 0x3CD,
    ANIMATION_ACTION_OLD_COOT_TALK_YES = 0x3CE,
    ANIMATION_ACTION_OLD_COOT_TALK_NO = 0x3CF,
    ANIMATION_ACTION_OLD_COOT_FLINCH = 0x3D0,
    ANIMATION_ACTION_OLD_COOT_FLINCH_RIGHT = 0x3D1,
    ANIMATION_ACTION_OLD_COOT_FLINCH_LEFT = 0x3D2,
    ANIMATION_ACTION_FACIAL_COVER = 0x3D3,
    ANIMATION_ACTION_FACIAL_FLINCH = 0x3D4,
    ANIMATION_ACTION_FACIAL_FIRE = 0x3D5,
    ANIMATION_ACTION_FACIAL_BLIND_FIRE = 0x3D6,
    ANIMATION_ACTION_DONT_USE = 0x3D7,
    NUM_ANIM_ACTIONS = 0x295,
};

enum human_ragdoll_state
{
    HUMAN_RAGDOLL_STATE_NONE = 0x0,
    HUMAN_RAGDOLL_STATE_ACTIVE = 0x1,
    HUMAN_RAGDOLL_STATE_BLEND_OUT = 0x2,
    HUMAN_RAGDOLL_STATE_FLINCH = 0x3,
    HUMAN_RAGDOLL_STATE_ACTIVE_ON_IMPACT = 0x4,
    HUMAN_RAGDOLL_STATE_DEACTIVATED = 0x5,
    HUMAN_RAGDOLL_STATE_POSE_SAVED = 0x6,
    NUM_HUMAN_RAGDOLL_STATES = 0x7,
};

struct human_flags
{
    unsigned __int32 bored_headtrack_disabled : 1;
    unsigned __int32 hidden : 1;
    unsigned __int32 cap_speed : 1;
    unsigned __int32 was_rendered : 1;
    unsigned __int32 locked_controller : 1;
    unsigned __int32 invulnerable : 1;
    unsigned __int32 mission_invulnerable : 1;
    unsigned __int32 no_damage : 1;
    unsigned __int32 activity_engage : 1;
    unsigned __int32 considered_armed : 1;
    unsigned __int32 riot_shield : 1;
    unsigned __int32 safehouse_vip : 1;
    unsigned __int32 radio_operator : 1;
    unsigned __int32 activity_raid_required : 1;
    unsigned __int32 activity_raid_optional : 1;
    unsigned __int32 activity_ha_hostage : 1;
    unsigned __int32 raid_introduction_lines : 1;
    unsigned __int32 miner_persona_lines : 1;
    unsigned __int32 damaged_by_player : 1;
    unsigned __int32 ai_ignore : 1;
    unsigned __int32 casts_shadows : 1;
    unsigned __int32 casts_drop_shadows : 1;
    unsigned __int32 is_turning : 1;
    unsigned __int32 is_falling : 1;
    unsigned __int32 dont_deform_bones : 1;
    unsigned __int32 dont_lod_bones : 1;
    unsigned __int32 playing_equip_anim : 1;
    unsigned __int32 playing_unequip_anim : 1;
    unsigned __int32 do_instant_equip : 1;
    unsigned __int32 anim_direct_blend : 1;
    unsigned __int32 start_jump : 1;
    unsigned __int32 super_jump : 1;
    unsigned __int32 processed_this_frame : 1;
    unsigned __int32 silent_vehicle_start : 1;
    unsigned __int32 suppress_flee_on_vehicle_exit : 1;
    unsigned __int32 death_func_done : 1;
    unsigned __int32 fading_in : 1;
    unsigned __int32 fading_out : 1;
    unsigned __int32 fading_out_from_nano : 1;
    unsigned __int32 is_nano_effect_currently_applied : 1;
    unsigned __int32 on_fire : 1;
    unsigned __int32 dropped_cash : 1;
    unsigned __int32 on_mover : 1;
    unsigned __int32 recalculate_at_node : 1;
    unsigned __int32 spinebending_done : 1;
    unsigned __int32 last_dest_in_repulsor : 1;
    unsigned __int32 jumping_from_building : 1;
    unsigned __int32 is_on_ladder : 1;
    unsigned __int32 ladder_force_slide : 1;
    unsigned __int32 ladder_force_exit : 1;
    unsigned __int32 ladder_reequip_weapon : 1;
    unsigned __int32 allow_flying_equips : 1;
    unsigned __int32 corpse_spotted : 1;
    unsigned __int32 corpse_spotted_by_enemy : 1;
    unsigned __int32 death_reported : 1;
    unsigned __int32 raid_death_ack : 1;
    unsigned __int32 anchor_orient : 1;
    unsigned __int32 bones_transformed_this_frame : 1;
    unsigned __int32 use_current_velocity : 1;
    unsigned __int32 use_as_final_velocity : 1;
    unsigned __int32 aim_at_pos : 1;
    unsigned __int32 block_forced_movement : 1;
    unsigned __int32 cancelling_melee_attack : 1;
    unsigned __int32 do_continuous_melee_damage : 1;
    unsigned __int32 in_air_melee : 1;
    unsigned __int32 cant_hit_with_melee : 1;
    unsigned __int32 invulnerable_to_debris : 1;
    unsigned __int32 override_default_anim_state : 1;
    unsigned __int32 override_default_fire_anim : 1;
    unsigned __int32 moving_and_transitioning_states : 1;
    unsigned __int32 check_for_cover : 1;
    unsigned __int32 jump_take_off : 1;
    unsigned __int32 rotate_internal_heading_updated : 1;
    unsigned __int32 crouch_cover : 1;
    unsigned __int32 cover_crouch_high_only : 1;
    unsigned __int32 cover_crouch_no_lean : 1;
    unsigned __int32 side_firing : 1;
    unsigned __int32 side_firing_walk_back : 1;
    unsigned __int32 ragdoll_on_impact_all_collisions : 1;
    unsigned __int32 ragdoll_on_impact_use_ragdoll_pos : 1;
    unsigned __int32 dive_capsule : 1;
    unsigned __int32 maintain_ambient_props : 1;
    unsigned __int32 leaning_disabled : 1;
    unsigned __int32 override_steering_heading_offset : 1;
    unsigned __int32 pushes_other_humans : 1;
    unsigned __int32 pushes_debris_scripted : 1;
    unsigned __int32 allow_steep_slopes : 1;
    unsigned __int32 external_force_applied : 1;
    unsigned __int32 ragdoll_shot : 1;
    unsigned __int32 saved_pushes_debris_scripted : 1;
    unsigned __int32 filter_handle_valid : 1;
    unsigned __int32 just_got_up_from_ragdoll : 1;
    unsigned __int32 disable_path_smoothing_for_request : 1;
    unsigned __int32 disable_all_path_smoothing : 1;
    unsigned __int32 in_fetal_position : 1;
    unsigned __int32 disallow_vehicle_exit : 1;
    unsigned __int32 limited_vehicle_exit : 1;
    unsigned __int32 driverless_exit_only : 1;
    unsigned __int32 stuck_in_vehicle : 1;
    unsigned __int32 convoy_vehicle_exit : 1;
    unsigned __int32 disallow_vehicle_entry : 1;
    unsigned __int32 disallow_vehicle_drive : 1;
    unsigned __int32 ambient_edf : 1;
    unsigned __int32 bashed_character_controller : 1;
    unsigned __int32 head_loaded : 1;
    unsigned __int32 lod_head_loaded : 1;
    unsigned __int32 in_vehicle_invisible : 1;
    unsigned __int32 high_priority_target : 1;
    unsigned __int32 health_change_was_negative : 1;
    unsigned __int32 voice_line_play_2d : 1;
    unsigned __int32 voice_line_pain_only : 1;
    unsigned __int32 killed_by_killzone : 1;
    unsigned __int32 first_time_streamed : 1;
    unsigned __int32 tired : 1;
    unsigned __int32 use_bigsteps : 1;
    unsigned __int32 stuck : 1;
    unsigned __int32 last_pf_failed : 1;
    unsigned __int32 extended_stuck : 1;
    unsigned __int32 xray_visible : 1;
    unsigned __int32 was_gibbed : 1;
    unsigned __int32 prevent_ragdoll_sfx : 1;
    unsigned __int32 always_show_on_minimap : 1;
    unsigned __int32 used_death_buffer : 1;
    unsigned __int32 do_not_convert_to_guerrilla : 1;
    unsigned __int32 do_not_play_ambient_or_greet_lines : 1;
    unsigned __int32 disallow_flinches_and_ragdolls : 1;
    unsigned __int32 only_use_action_nodes : 1;
    unsigned __int32 complain_when_shot : 1;
};

struct human_mp_flags
{
    unsigned __int32 is_multiplayer : 1;
    unsigned __int32 melee_primary_id : 2;
    unsigned __int32 melee_secondary_id : 2;
    unsigned __int32 melee_tertiary_id : 2;
    unsigned __int32 melee_firearm_id : 2;
    unsigned __int32 jump_id : 2;
    unsigned __int32 vehicle : 1;
    unsigned __int32 turret : 1;
    unsigned __int32 swap_weapon : 1;
    unsigned __int32 firearm_trigger_down_id : 2;
    unsigned __int32 firearm_trigger_up_id : 2;
    unsigned __int32 throw_attack_id : 2;
    unsigned __int32 charge_weapon : 2;
    unsigned __int32 running_attack : 1;
    unsigned __int32 in_air_detonate : 1;
    unsigned __int32 detonated_charges : 1;
    unsigned __int32 jetpack : 1;
};

struct weapon_anim_flags
{
    unsigned __int32 prone : 1;
    unsigned __int32 crouch : 1;
    unsigned __int32 down_ready : 1;
    unsigned __int32 ready : 1;
    unsigned __int32 aim : 1;
    unsigned __int32 fine_aim : 1;
    unsigned __int32 no_ammo : 1;
    unsigned __int32 walk : 1;
    unsigned __int32 run : 1;
    unsigned __int32 left : 1;
    unsigned __int32 right : 1;
    unsigned __int32 back : 1;
    unsigned __int32 backpedal : 1;
    unsigned __int32 switching : 1;
    unsigned __int32 drive : 1;
    unsigned __int32 ride : 1;
    unsigned __int32 ride_left : 1;
};

enum ik_type
{
    ANIMATION_IK_LEFT_HAND = 0x0,
    ANIMATION_IK_RIGHT_HAND = 0x1,
    ANIMATION_IK_LEFT_FOOT = 0x2,
    ANIMATION_IK_RIGHT_FOOT = 0x3,
    NUM_ANIMATION_IK_TYPES = 0x4,
};

struct  ik_joint
{
    int anchor_tag;
    int joint_tag;
    int ik_tag;
    float ik_strength;
    float ik_rate_of_change;
    unsigned int freeze_obj_handle;
    vector freeze_offset_pos;
    ik_type location;
};

struct path_node_flags//$CAF8DE907F29E1426E7531D75E1C3ADA
{
    __int8 do_not_remove : 1;
    __int8 jumping : 1;
    __int8 dropping_down : 1;
    __int8 leap_over : 1;
    __int8 ladder : 1;
    __int8 optimized : 1;
    __int8 off_navmesh : 1;
    __int8 bridge : 1;
    __int8 stairs : 1;
};

struct __declspec(align(4)) path_node
{
    path_node* next;
    path_node* prev;
    vector pos;
    unsigned __int64 nav_cell_handle;
    unsigned int navpoint_handle;
    vector normal;
    float distance_left;
    unsigned int compound_hull_handle;
    int compound_hull_vert_index;
    path_node_flags flags;
};

struct human_path_data_flags//$44C0BA19B9554B4F1413675B767343EF
{
    __int8 turn_right : 1;
    __int8 smoothing : 1;
    __int8 climbing_up : 1;
};

struct __declspec(align(8)) human_path_data
{
    human_path_actions action;
    human_movement_states prev_state;
    path_node* path;
    timestamp shortcut_time;
    timestamp dest_in_hull_time;
    vector start_pos;
    unsigned __int64 last_visited_nav_cell_handle;
    timestamp last_visited_nav_cell_update_timer;
    timestamp dest_check_timer;
    vector last_dest_check_pos;
    int extended_stuck_cumulative;
    timestamp extended_stuck_timer;
    vector extended_stuck_pos;
    timestamp detour_hull_check_timer;
    unsigned int problem_detour_handles[4];
    int num_problem_detours;
    vector problem_detours_dest_pos;
    char affected_by_repulsors;
    char num_path_repulsors;
    unsigned int path_repulsor_handles[8];
    timestamp path_repulsors_collection_time;
    timestamp repulsion_field_timer;
    timestamp hole_repulsion_field_timer;
    vector eventual_goal_pos;
    float dist_until_recheck;
    char num_hole_repulsors;
    unsigned int hole_repulsors[8];
    unsigned int last_cmp_hull;
    unsigned int transition_node_to_avoid;
    float movement_radius;
    float curve_distance;
    vector smoothPoint;
    vector center_of_circle;
    vector smooth_start_pos;
    vector smooth_start_fvec;
    human_path_data_flags flags;
};

struct object_render_distance
{
    float apparent_distance;
    int last_frame_processed;
};

struct character_instance
{
    struct resource_dependent_data
    {
        void* base_character; //character* base_character;
        void* renderable_instance_p; //rl_skin_instance* renderable_instance_p;
    };

    int aim_handle;
    void* vp;//v_animate* vp;
    float orig_character_scale;
    float character_scale;
    unsigned __int16 ci_flags;
    char render_alpha;
    char cache_lod;
    int buf_verts_shadow_offset;
    char* buf_frame_verts;
    character_instance* next;
    character_instance* prev;
    unsigned int variant_index;
    float bbox_max_dimension;
    object_stream_resource<character_instance::resource_dependent_data> rdd;
};

struct spinebend_bone_state_flags //$F0753B8D73BBECCB8B73BA0CFB418925
{
    unsigned __int32 fast_mode : 1;
};

/* 4166 */
struct spinebend_bone_state
{
    float heading;
    float pitch;
    float desired_heading;
    float desired_pitch;
    float last_heading;
    float last_pitch;
    float anim_last_bone_heading;
    float anim_last_bone_pitch;
    float anim_heading_change;
    float anim_pitch_change;
    float max_children_heading;
    float min_children_heading;
    float max_children_pitch;
    float min_children_pitch;
    float children_total_blend;
    float max_pitch;
    float min_pitch;
    float max_heading;
    float min_heading;
    float heading_vel;
    float pitch_vel;
    int bone_index;
    int rig_bone_parent;
    spinebend_bone_state_flags flags;
};

struct spinebend_flags
{
    unsigned __int32 disabled : 1;
    unsigned __int32 track_object : 1;
    unsigned __int32 sleep_mode : 1;
    unsigned __int32 sleep_mode_ready : 1;
    unsigned __int32 no_spinebending_last_frame : 1;
    unsigned __int32 do_spinebend_process : 1;
    unsigned __int32 zero_pitch : 1;
    unsigned __int32 zero_heading : 1;
    unsigned __int32 zero_eye_pitch : 1;
    unsigned __int32 zero_eye_heading : 1;
    unsigned __int32 force_update : 1;
    unsigned __int32 is_player : 1;
    unsigned __int32 delay_processing : 1;
    unsigned __int32 blending_anims : 1;
    unsigned __int32 spinebend_teleport : 1;
    unsigned __int32 linear_interpolation : 1;
    unsigned __int32 aim_at_pos : 1;
    unsigned __int32 pan_dir : 1;
};

enum spinebend_interest
{
    SI_CHOOSE_NEW_MAIN_FOCUS_PRIMARY = 0x0,
    SI_CHOOSE_NEW_MAIN_FOCUS = 0x1,
    SI_MAIN_FOCUS_PRIMARY = 0x2,
    SI_MAIN_FOCUS_RANDOM = 0x3,
    SI_HOLDING_FOCUS = 0x4,
    SI_LOCAL_SCANNING = 0x5,
    SI_PANNING_START = 0x6,
    SI_PANNING = 0x7,
    SI_PANNING_GLANCE = 0x8,
    SI_PANNING_FOLLOW = 0x9,
    SI_QUICK_GLANCE = 0xA,
    SI_FOLLOW_EYES = 0xB,
};

struct human_spinebend_data
{
    spinebend_flags flags;
    unsigned int target_object_handle;
    vector target_point;
    vector last_lookat_vec;
    spinebend_interest main_interest;
    spinebend_interest head_interest;
    spinebend_interest eyes_interest;
    spinebend_interest last_eyes_interest;
    vector head_dest_vec;
    vector eyes_dest_vec;
    float lookat_priority;
    float eye_lookat_priority;
    timestamp head_orient_ts;
    timestamp main_interest_ts;
    timestamp eyes_orient_ts;
    timestamp focus_target_ts;
    float pan_heading;
    timestamp pan_ts;
    timestamp update_timestamp;
    float remaining_heading;
    float lower_body_rotation;
    float lower_body_heading_speed;
    float spinebend_bone_rotation;
    float spinebend_bone_last_heading;
    float root_heading_change;
    float root_heading_last_frame;
    int spinebend_bone_index;
    float turn_speed;
    float heading_drift;
    float pitch_drift;
    unsigned int bone_filter;
    float bone_max_angle_multiplier;
    int aim_handle;
    vector state_controller_movement;
    spinebend_bone_state bone_state[9];
};

struct morph_target
{
    float blend;
    float blend_target;
    float blend_rate;
    int target_idx;
};

enum lipsync_data_handle
{
    INVALID_LIPSYNC_DATA_HANDLE = 0xFFFFFFFF,
    LIPSYNC_DATA_HANDLE_FORCE_TO_32_BIT = 0x7FFFFFFF,
};

struct __declspec(align(2)) human_head_morphing
{
    int num_targets;
    morph_target target[5];
    timestamp blink_ts;
    float blink_blend;
    lipsync_data_handle current_lipsync_handle;
    float emotion_scale;
    unsigned int current_phn_start;
    unsigned int initial_phn_start;
    unsigned int current_phn_end;
    int total_duration;
    timestamp timer;
    unsigned __int16 current_phn;
    __int8 do_blink_close : 1;
    __int8 do_blink_open : 1;
    __int8 do_blink_wait : 1;
    __int8 has_new_data : 1;
};

enum damaged_by_types
{
    DBT_NONE = 0x0,
    DBT_CAR = 0x1,
    DBT_EXPLOSION = 0x2,
    DBT_BULLET = 0x3,
    DBT_LEVEL_OBJECT = 0x4,
    DBT_MELEE = 0x5,
    DBT_WORLD = 0x6,
    DBT_RADIATION = 0x7,
};

struct human_combat
{
    unsigned int last_hit_by_handle;
    unsigned int last_hit_by_other_handle;
    unsigned int last_hit_by_weapon_handle;
    unsigned int last_hit_by_other_weapon_handle;
    damaged_by_types last_hit_by_damage_type;
    damaged_by_types last_hit_by_other_damage_type;
    int last_hit_time_ms;
    int last_hit_by_other_time_ms;
    unsigned int last_killed_by_handle;
    unsigned int last_killed_by_other_handle;
    int last_killed_time_ms;
    int last_killed_by_other_time_ms;
    vector last_killed_pos;
    unsigned int last_kill_handle;
    unsigned int last_kill_other_handle;
    int last_kill_time_ms;
    int last_kill_other_time_ms;
    unsigned int target_handle;
    unsigned int targets_building_handle;
    void* cur_melee_combat_move; //human_melee_combat_move_data* cur_melee_combat_move;
    int hit_object_count;
    vector last_continuous_pos;
    vector last_continuous_pos_2;
    bool played_hit_effect;
    float current_flank_offset;
    float flank_delta;
    timestamp melee_damage_timer;
    timestamp combat_maneuver_timestamp;
    timestamp no_path_to_target_timestamp;
    timestamp dodge_timestamp;
    timestamp hold_trigger_timestamp;
    timestamp shoot_enemy_timestamp;
    timestamp move_to_melee_timestamp;
    timestamp melee_attack_interval_timer;
    timestamp flinch_timestamp;
    timestamp melee_delay_timer;
    timestamp beaten_up_timer;
    timestamp combat_ready_timestamp;
    timestamp combat_aim_timestamp;
    timestamp combat_blindfire_timestamp;
    timestamp pursuit_timestamp;
    timestamp last_pursuit_timestamp;
    timestamp throw_grenade_timestamp;
    unsigned int thrown_weapon;
    vector throw_velocity;
    bool thrown_weapon_released;
    unsigned int last_projectile_handle;
    unsigned int reserved_cover_node;
    unsigned int reserved_turret;
    timestamp not_undercover_timestamp;
    timestamp pain_sound_timestamp;
};

struct checksum_stri
{
    unsigned int checksum;
};

struct inv_item_info
{
    char* name;
    checksum_stri name_checksum;
    char* display_name;
    int cost;
    int default_count;
    int max_item;
    char* description;
    void* w_info; //weapon_info* w_info;
    char item_order;
    bool(__cdecl* use)();
};

struct inventory_item
{
    inventory_item* next;
    inventory_item* prev;
    inv_item_info* info;
    int count;
    int selection_slot;
    int attachment_prop;
    unsigned int weapon_handle;
};

struct nano_callback_info
{
    unsigned int target_handle;
    bool killed_by_nano;
    int human_nano_index;
};

struct __declspec(align(4)) human_action_node_data
{
    farray<unsigned int, 4> action_node_set;
    int action_state;
    int action_sub_state;
    int existing_action_state;
    unsigned int current_action_node;
    timestamp state_duration;
    bool exit_quick;
};

struct Human : Object
{
    struct raycast_hit_info_data
    {
        vector fire_pos;
        vector target_pos;
        vector hit_point;
        object_hit_location hit_location;
        int hit_bone;
    };

    struct resource_dependent_data
    {
        void* controller; //character_controller* controller;
        void* hit_detect_phantom; //hkpSimpleShapePhantom* hit_detect_phantom;
        void* head_renderable_instance_p; //rl_skin_instance* head_renderable_instance_p;
        int head_aim_handle;
        int head_manager_idx;
    };

    object_stream_resource<Human::resource_dependent_data> rdd;
    human_flags hflags;
    human_mp_flags mp_flags;
    int last_trigger_down_frame;
    void* h_info; //human_info* h_info;
    object_render_distance render_distance;
    char xray_material;
    char xray_render_alpha;
    int rank;
    vector approx_local_bmin;
    vector approx_local_bmax;
    vector last_pos;
    human_path_data pf;
    vector turnto_target;
    unsigned int nav_cell_detour_request_handle;
    Human::raycast_hit_info_data raycast_hit_info;
    vector velocity;
    vector actual_velocity;
    int transform_frames_skipped;
    vector steering_vector;
    float move_speed;
    float steering_heading_offset;
    human_rotate_dir rotate_dir;
    float state_speed_throttle;
    float rotate_heading_left;
    float rotate_heading_right;
    float rotate_internal_heading;
    vector inertial_motion;
    unsigned int ground_obj_handle;
    vector ground_obj_contact_pos;
    int ground_obj_alt_body_idx;
    int ground_obj_shape_key;
    float ground_obj_normal;
    unsigned int object_filter_handle;
    int block_movement_anim;
    vector block_steering_vector;
    block_movement_types block_movement_type;
    float block_steering_heading_offset;
    int released_movement_anim;
    block_movement_types released_movement_type;
    human_states cur_state;
    human_movement_states cur_movement_state;
    human_stances cur_stance;
    human_stances last_stance;
    human_move_modes movement_mode;
    human_move_submodes movement_submode;
    human_move_modes previous_movement_mode;
    animation_action custom_fire_animation;
    float walk_animation_speed_pct;
    float frametime_tally;
    float actual_velocity_mag;
    float max_speed;
    float falling_vel_mag;
    timestamp not_moving_update;
    character_instance* char_inst;
    void* cloth_sim; //cloth_simulation* cloth_sim;
    int bone_lod_level;
    weapon_anim_flags animation_flags;
    human_ragdoll_state ragdoll_state;
    unsigned int ragdoll_source_human_handle;
    int ragdoll_idx;
    float ragdoll_blend_pct;
    vector ragdoll_last_frame_velocity;
    float ragdoll_on_impact_time;
    float ragdoll_on_impact_min_vel;
    timestamp ragdoll_damaged;
    float root_bone_offset;
    unsigned int nano_mat_fx[16];
    unsigned int mat_fx_handle_for_head_skin;
    unsigned int last_valid_pos_before_ragdoll_index;
    vector last_valid_pos_before_ragdoll[3];
    int ragdoll_num_collisions_with_walker;
    ik_joint ik_joints[4];
    __declspec(align(16)) human_spinebend_data spinebend_data;
    human_head_morphing head_morphs;
    int initial_max_hit_points;
    int max_hit_points;
    float hit_points;
    int max_knockdown_hits;
    float knockdown_hits;
    timestamp knockdown_timestamp;
    timestamp knockdown_timeout_ts;
    human_combat combat;
    timestamp collision_damage_timer;
    float current_collision_damage;
    timestamp do_ragdoll_ts;
    timestamp facial_pose_ts;
    timestamp turret_hold_animations;
    float cash;
    inventory_item* inventory;
    inventory_item* desired_equipped_inv_item;
    inventory_item* last_equipped_weapon;
    inventory_item* second_last_equipped_weapon;
    inventory_item* grenade_weapon;
    void* anim_prop_info; //item_info* anim_prop_info;
    unsigned int offhand_projectile_handle;
    unsigned int shield_handle;
    timestamp reload_timer;
    int equip_tag_index;
    int equip_offhand_tag_index;
    int root_bone_index;
    int left_foot_bone_index;
    int right_foot_bone_index;
    int left_shoulder_bone_index;
    int right_shoulder_bone_index;
    int left_hand_bone_index;
    int right_hand_bone_index;
    int left_hip_bone_index;
    int right_hip_bone_index;
    float run_stand_blend_pose_weight;
    float lean_weight;
    vector lean_dir;
    timestamp lean_disabled;
    vector lean_last_steering_vector;
    foot_plant foot_planted;
    timestamp foot_plant_time;
    bool is_turning;
    bool starting_turn;
    float render_alpha;
    float camera_alpha_override;
    bool casts_transparent_shadows;
    timestamp fade_timer;
    int fade_time;
    float m_stealth_percent;
    unsigned int vehicle_handle;
    unsigned int reserved_vehicle_handle;
    vehicle_seat_index vehicle_seat_idx;
    timestamp bored_idle_timestamp;
    timestamp corpse_cleanup_timer;
    timestamp turn_off_fire_timestamp;
    timestamp health_restore_timestamp;
    float health_restore_hit_points;
    float health_restore_min_hit_points;
    vector look_at_pos;
    unsigned int look_at_handle;
    float look_at_speed;
    vector aim_override_dir;
    float damage_percent;
    unsigned __int16 damage_func_handle;
    unsigned __int16 death_func_handle;
    timestamp breath_timer;
    timestamp crouch_to_stand_test_ts;
    unsigned int ladder_handle;
    float ladder_slide_speed;
    int ladder_grab_rung;
    int ladder_slide_play_id;
    bool code_driven_start_jump;
    float code_driven_jump_timer;
    float code_driven_jump_height;
    timestamp jump_state_timer;
    timestamp last_supported;
    timestamp air_time;
    timestamp update_timer;
    object_importance_level importance_level;
    unsigned int scripted_action_node_handle;
    nano_callback_info nano_cb_info[16];
    int nano_index;
    human_action_node_data action_node_data;
    unsigned int light_effects[2];
    int light_tags[2];
    timestamp avoidance_check_timer;
    timestamp avoidance_request_timer;
    unsigned int avoidance_request_human;
    vector avoidance_move_dir;
    vector avoidance_hint_dir;
    timestamp avoidance_pause_timer;
    human_movement_states avoidance_original_movement_state;
    int minimap_flags;
    void* amb_prop_info; //ambient_prop_info* amb_prop_info;
    inventory_item* equipped_inv_item_last_frame;
    inventory_item* equipped_inv_item;
    void* voice; //human_voice_persona* voice;
    human_teams current_team;
    human_teams undercover_team;
    int dialogue_foley_info;
    voice_line_handle queued_voice_line;
    voice_lines situational_voice_line;
    voice_line_priorities voice_priority;
    audiolib_cue_priority voice_cue_priority;
    unsigned __int16 radio_instance;
    int voice_instance;
    timestamp voice_time_since_finish;
    lipsync_data_handle lipsync_handle;
    timestamp voice_delay_time;
    bool(__cdecl* voice_delay_cb)(Human*, void*);
    void* voice_delay_cb_data;
    timestamp acknowledged_time;
    timestamp reported_timer;
    timestamp lifetime;
};