#include "ImportedFunctions.h"

F_ext_GetGlobalState ext_GetGlobalState = nullptr;
F_ext_GetRfgFunctions ext_GetRfgFunctions = nullptr;
F_ext_GetImGuiContext ext_GetImGuiContext = nullptr;
F_ext_RegisterImGuiCallback ext_RegisterImGuiCallback = nullptr;
F_ext_RemoveImGuiCallback ext_RemoveImGuiCallback = nullptr;
F_ext_RegisterOverlayCallback ext_RegisterOverlayCallback = nullptr;
F_ext_RemoveOverlayCallback ext_RemoveOverlayCallback = nullptr;
F_ext_RegisterPrimitiveDrawCallback ext_RegisterPrimitiveDrawCallback = nullptr;
F_ext_RemovePrimitiveDrawCallback ext_RemovePrimitiveDrawCallback = nullptr;